version: "3.8"

services:
  db:
    image: postgres:15
    container_name: finance_db
    restart: always
    environment:
      POSTGRES_USER: finance_user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: financedb
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
