// This file is auto-generated by @hey-api/openapi-ts

export const Body_bulk_import_upload_fileSchema = {
    properties: {
        file: {
            type: 'string',
            format: 'binary',
            title: 'File'
        }
    },
    type: 'object',
    required: ['file'],
    title: 'Body_bulk-import-upload_file'
} as const;

export const Body_login_login_access_tokenSchema = {
    properties: {
        grant_type: {
            anyOf: [
                {
                    type: 'string',
                    pattern: 'password'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Grant Type'
        },
        username: {
            type: 'string',
            title: 'Username'
        },
        password: {
            type: 'string',
            title: 'Password'
        },
        scope: {
            type: 'string',
            title: 'Scope',
            default: ''
        },
        client_id: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Client Id'
        },
        client_secret: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Client Secret'
        }
    },
    type: 'object',
    required: ['username', 'password'],
    title: 'Body_login-login_access_token'
} as const;

export const Body_media_upload_imageSchema = {
    properties: {
        file: {
            type: 'string',
            format: 'binary',
            title: 'File'
        }
    },
    type: 'object',
    required: ['file'],
    title: 'Body_media-upload_image'
} as const;

export const BulkImportFinalRequestSchema = {
    properties: {
        session_id: {
            type: 'string',
            format: 'uuid',
            title: 'Session Id'
        },
        skip_errors: {
            type: 'boolean',
            title: 'Skip Errors',
            default: true
        },
        duplicate_action: {
            type: 'string',
            title: 'Duplicate Action',
            default: 'skip'
        },
        tags: {
            items: {
                type: 'string'
            },
            type: 'array',
            title: 'Tags',
            default: []
        },
        notes: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Notes'
        }
    },
    type: 'object',
    required: ['session_id'],
    title: 'BulkImportFinalRequest',
    description: 'Final import request with options.'
} as const;

export const BulkImportResultSchema = {
    properties: {
        import_id: {
            type: 'string',
            format: 'uuid',
            title: 'Import Id'
        },
        session_id: {
            type: 'string',
            format: 'uuid',
            title: 'Session Id'
        },
        success_count: {
            type: 'integer',
            title: 'Success Count'
        },
        error_count: {
            type: 'integer',
            title: 'Error Count'
        },
        duplicate_count: {
            type: 'integer',
            title: 'Duplicate Count'
        },
        total_processed: {
            type: 'integer',
            title: 'Total Processed'
        },
        duration_seconds: {
            type: 'number',
            title: 'Duration Seconds'
        },
        imported_product_ids: {
            items: {
                type: 'string',
                format: 'uuid'
            },
            type: 'array',
            title: 'Imported Product Ids',
            default: []
        },
        errors: {
            items: {
                additionalProperties: true,
                type: 'object'
            },
            type: 'array',
            title: 'Errors',
            default: []
        }
    },
    type: 'object',
    required: ['import_id', 'session_id', 'success_count', 'error_count', 'duplicate_count', 'total_processed', 'duration_seconds'],
    title: 'BulkImportResult',
    description: 'Final result of bulk import.'
} as const;

export const BulkImportSessionPublicSchema = {
    properties: {
        filename: {
            type: 'string',
            maxLength: 255,
            title: 'Filename'
        },
        total_rows: {
            type: 'integer',
            minimum: 0,
            title: 'Total Rows'
        },
        valid_rows: {
            type: 'integer',
            minimum: 0,
            title: 'Valid Rows',
            default: 0
        },
        error_rows: {
            type: 'integer',
            minimum: 0,
            title: 'Error Rows',
            default: 0
        },
        duplicate_rows: {
            type: 'integer',
            minimum: 0,
            title: 'Duplicate Rows',
            default: 0
        },
        imported_rows: {
            type: 'integer',
            minimum: 0,
            title: 'Imported Rows',
            default: 0
        },
        status: {
            type: 'string',
            maxLength: 50,
            title: 'Status',
            default: 'uploaded'
        },
        column_mapping: {
            anyOf: [
                {
                    additionalProperties: true,
                    type: 'object'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Column Mapping'
        },
        import_options: {
            anyOf: [
                {
                    additionalProperties: true,
                    type: 'object'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Import Options'
        },
        duplicate_action: {
            type: 'string',
            maxLength: 20,
            title: 'Duplicate Action',
            default: 'skip'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        },
        completed_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Completed At'
        },
        columns: {
            anyOf: [
                {
                    items: {
                        type: 'string'
                    },
                    type: 'array'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Columns'
        },
        auto_mapping: {
            anyOf: [
                {
                    additionalProperties: true,
                    type: 'object'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Auto Mapping'
        }
    },
    type: 'object',
    required: ['filename', 'total_rows', 'id', 'created_at'],
    title: 'BulkImportSessionPublic'
} as const;

export const BulkImportValidationResponseSchema = {
    properties: {
        session_id: {
            type: 'string',
            format: 'uuid',
            title: 'Session Id'
        },
        rows: {
            items: {
                '$ref': '#/components/schemas/ImportRow'
            },
            type: 'array',
            title: 'Rows'
        },
        total_count: {
            type: 'integer',
            title: 'Total Count'
        },
        valid_count: {
            type: 'integer',
            title: 'Valid Count'
        },
        error_count: {
            type: 'integer',
            title: 'Error Count'
        },
        duplicate_count: {
            type: 'integer',
            title: 'Duplicate Count'
        }
    },
    type: 'object',
    required: ['session_id', 'rows', 'total_count', 'valid_count', 'error_count', 'duplicate_count'],
    title: 'BulkImportValidationResponse',
    description: 'Response for validation endpoint.'
} as const;

export const ColumnMappingRequestSchema = {
    properties: {
        session_id: {
            type: 'string',
            format: 'uuid',
            title: 'Session Id'
        },
        column_mapping: {
            additionalProperties: true,
            type: 'object',
            title: 'Column Mapping'
        },
        default_category_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Default Category Id'
        },
        default_status_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Default Status Id'
        }
    },
    type: 'object',
    required: ['session_id', 'column_mapping'],
    title: 'ColumnMappingRequest',
    description: 'Request model for column mapping.'
} as const;

export const ColumnMappingResponseSchema = {
    properties: {
        session_id: {
            type: 'string',
            format: 'uuid',
            title: 'Session Id'
        },
        total_rows: {
            type: 'integer',
            title: 'Total Rows'
        },
        valid_rows: {
            type: 'integer',
            title: 'Valid Rows'
        },
        error_rows: {
            type: 'integer',
            title: 'Error Rows'
        },
        duplicate_rows: {
            type: 'integer',
            title: 'Duplicate Rows'
        },
        preview_rows: {
            items: {
                '$ref': '#/components/schemas/ImportRow'
            },
            type: 'array',
            title: 'Preview Rows'
        }
    },
    type: 'object',
    required: ['session_id', 'total_rows', 'valid_rows', 'error_rows', 'duplicate_rows', 'preview_rows'],
    title: 'ColumnMappingResponse',
    description: 'Response after column mapping with validation results.'
} as const;

export const FixRowRequestSchema = {
    properties: {
        session_id: {
            type: 'string',
            format: 'uuid',
            title: 'Session Id'
        },
        row_number: {
            type: 'integer',
            title: 'Row Number'
        },
        updated_data: {
            additionalProperties: true,
            type: 'object',
            title: 'Updated Data'
        }
    },
    type: 'object',
    required: ['session_id', 'row_number', 'updated_data'],
    title: 'FixRowRequest',
    description: 'Request to fix a specific row.'
} as const;

export const HTTPValidationErrorSchema = {
    properties: {
        detail: {
            items: {
                '$ref': '#/components/schemas/ValidationError'
            },
            type: 'array',
            title: 'Detail'
        }
    },
    type: 'object',
    title: 'HTTPValidationError'
} as const;

export const ImportRowSchema = {
    properties: {
        row_number: {
            type: 'integer',
            title: 'Row Number'
        },
        data: {
            additionalProperties: true,
            type: 'object',
            title: 'Data'
        },
        mapped_data: {
            anyOf: [
                {
                    additionalProperties: true,
                    type: 'object'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Mapped Data'
        },
        errors: {
            items: {
                '$ref': '#/components/schemas/ValidationError'
            },
            type: 'array',
            title: 'Errors',
            default: []
        },
        warnings: {
            items: {
                type: 'string'
            },
            type: 'array',
            title: 'Warnings',
            default: []
        },
        is_duplicate: {
            type: 'boolean',
            title: 'Is Duplicate',
            default: false
        },
        duplicate_product_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Duplicate Product Id'
        },
        status: {
            type: 'string',
            title: 'Status',
            default: 'valid'
        }
    },
    type: 'object',
    required: ['row_number', 'data'],
    title: 'ImportRow',
    description: 'Represents a single row in the bulk import.'
} as const;

export const MediaPublicSchema = {
    properties: {
        file_path: {
            type: 'string',
            maxLength: 500,
            title: 'File Path'
        },
        file_name: {
            type: 'string',
            maxLength: 255,
            title: 'File Name'
        },
        mime_type: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 100
                },
                {
                    type: 'null'
                }
            ],
            title: 'Mime Type'
        },
        size: {
            type: 'integer',
            title: 'Size'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        },
        url: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Url'
        }
    },
    type: 'object',
    required: ['file_path', 'file_name', 'size', 'id', 'created_at'],
    title: 'MediaPublic'
} as const;

export const MessageSchema = {
    properties: {
        message: {
            type: 'string',
            title: 'Message'
        }
    },
    type: 'object',
    required: ['message'],
    title: 'Message'
} as const;

export const NewPasswordSchema = {
    properties: {
        token: {
            type: 'string',
            title: 'Token'
        },
        new_password: {
            type: 'string',
            maxLength: 40,
            minLength: 8,
            title: 'New Password'
        }
    },
    type: 'object',
    required: ['token', 'new_password'],
    title: 'NewPassword'
} as const;

export const PaymentMethodPublicSchema = {
    properties: {
        name: {
            type: 'string',
            maxLength: 100,
            title: 'Name'
        },
        description: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 500
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        }
    },
    type: 'object',
    required: ['name', 'id'],
    title: 'PaymentMethodPublic'
} as const;

export const PaymentMethodsPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/PaymentMethodPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'PaymentMethodsPublic'
} as const;

export const PrivateUserCreateSchema = {
    properties: {
        email: {
            type: 'string',
            title: 'Email'
        },
        password: {
            type: 'string',
            title: 'Password'
        },
        full_name: {
            type: 'string',
            title: 'Full Name'
        },
        is_verified: {
            type: 'boolean',
            title: 'Is Verified',
            default: false
        }
    },
    type: 'object',
    required: ['email', 'password', 'full_name'],
    title: 'PrivateUserCreate'
} as const;

export const ProductCategoriesPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/ProductCategoryPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'ProductCategoriesPublic'
} as const;

export const ProductCategoryPublicSchema = {
    properties: {
        name: {
            type: 'string',
            maxLength: 255,
            title: 'Name'
        },
        description: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 500
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        }
    },
    type: 'object',
    required: ['name', 'id', 'created_at'],
    title: 'ProductCategoryPublic'
} as const;

export const ProductCreateSchema = {
    properties: {
        name: {
            type: 'string',
            maxLength: 255,
            title: 'Name'
        },
        description: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 1000
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        buying_price: {
            anyOf: [
                {
                    type: 'number',
                    exclusiveMinimum: 0
                },
                {
                    type: 'string',
                    pattern: '^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d{0,2}0*$'
                }
            ],
            title: 'Buying Price'
        },
        selling_price: {
            anyOf: [
                {
                    type: 'number',
                    exclusiveMinimum: 0
                },
                {
                    type: 'string',
                    pattern: '^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d{0,2}0*$'
                }
            ],
            title: 'Selling Price'
        },
        current_stock: {
            type: 'integer',
            minimum: 0,
            title: 'Current Stock',
            default: 0
        },
        reorder_level: {
            anyOf: [
                {
                    type: 'integer',
                    minimum: 0
                },
                {
                    type: 'null'
                }
            ],
            title: 'Reorder Level'
        },
        category_id: {
            type: 'string',
            format: 'uuid',
            title: 'Category Id'
        },
        status_id: {
            type: 'string',
            format: 'uuid',
            title: 'Status Id'
        },
        image_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Image Id'
        }
    },
    type: 'object',
    required: ['name', 'buying_price', 'selling_price', 'category_id', 'status_id'],
    title: 'ProductCreate'
} as const;

export const ProductPublicSchema = {
    properties: {
        name: {
            type: 'string',
            maxLength: 255,
            title: 'Name'
        },
        description: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 1000
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        buying_price: {
            type: 'string',
            pattern: '^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d{0,2}0*$',
            title: 'Buying Price'
        },
        selling_price: {
            type: 'string',
            pattern: '^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d{0,2}0*$',
            title: 'Selling Price'
        },
        current_stock: {
            type: 'integer',
            minimum: 0,
            title: 'Current Stock',
            default: 0
        },
        reorder_level: {
            anyOf: [
                {
                    type: 'integer',
                    minimum: 0
                },
                {
                    type: 'null'
                }
            ],
            title: 'Reorder Level'
        },
        category_id: {
            type: 'string',
            format: 'uuid',
            title: 'Category Id'
        },
        status_id: {
            type: 'string',
            format: 'uuid',
            title: 'Status Id'
        },
        image_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Image Id'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        },
        category: {
            '$ref': '#/components/schemas/ProductCategoryPublic'
        },
        status: {
            '$ref': '#/components/schemas/ProductStatusPublic'
        },
        image: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/MediaPublic'
                },
                {
                    type: 'null'
                }
            ]
        }
    },
    type: 'object',
    required: ['name', 'buying_price', 'selling_price', 'category_id', 'status_id', 'id', 'created_at', 'category', 'status', 'image'],
    title: 'ProductPublic'
} as const;

export const ProductStatusPublicSchema = {
    properties: {
        name: {
            type: 'string',
            maxLength: 100,
            title: 'Name'
        },
        description: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 500
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        }
    },
    type: 'object',
    required: ['name', 'id'],
    title: 'ProductStatusPublic'
} as const;

export const ProductUpdateSchema = {
    properties: {
        name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Name'
        },
        description: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 1000
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        buying_price: {
            anyOf: [
                {
                    type: 'number',
                    exclusiveMinimum: 0
                },
                {
                    type: 'string',
                    pattern: '^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d{0,2}0*$'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Buying Price'
        },
        selling_price: {
            anyOf: [
                {
                    type: 'number',
                    exclusiveMinimum: 0
                },
                {
                    type: 'string',
                    pattern: '^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d{0,2}0*$'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Selling Price'
        },
        current_stock: {
            anyOf: [
                {
                    type: 'integer',
                    minimum: 0
                },
                {
                    type: 'null'
                }
            ],
            title: 'Current Stock'
        },
        reorder_level: {
            anyOf: [
                {
                    type: 'integer',
                    minimum: 0
                },
                {
                    type: 'null'
                }
            ],
            title: 'Reorder Level'
        },
        category_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Category Id'
        },
        status_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Status Id'
        },
        image_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Image Id'
        }
    },
    type: 'object',
    title: 'ProductUpdate'
} as const;

export const ProductsPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/ProductPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'ProductsPublic'
} as const;

export const SaleCreateSchema = {
    properties: {
        product_id: {
            type: 'string',
            format: 'uuid',
            title: 'Product Id'
        },
        quantity: {
            type: 'integer',
            exclusiveMinimum: 0,
            title: 'Quantity'
        },
        unit_price: {
            anyOf: [
                {
                    type: 'number',
                    exclusiveMinimum: 0
                },
                {
                    type: 'string',
                    pattern: '^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d{0,2}0*$'
                }
            ],
            title: 'Unit Price'
        },
        total_amount: {
            anyOf: [
                {
                    type: 'number',
                    exclusiveMinimum: 0
                },
                {
                    type: 'string',
                    pattern: '^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d{0,2}0*$'
                }
            ],
            title: 'Total Amount'
        },
        payment_method_id: {
            type: 'string',
            format: 'uuid',
            title: 'Payment Method Id'
        },
        customer_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Customer Name'
        },
        notes: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 1000
                },
                {
                    type: 'null'
                }
            ],
            title: 'Notes'
        }
    },
    type: 'object',
    required: ['product_id', 'quantity', 'unit_price', 'total_amount', 'payment_method_id'],
    title: 'SaleCreate'
} as const;

export const SalePublicSchema = {
    properties: {
        product_id: {
            type: 'string',
            format: 'uuid',
            title: 'Product Id'
        },
        quantity: {
            type: 'integer',
            exclusiveMinimum: 0,
            title: 'Quantity'
        },
        unit_price: {
            type: 'string',
            pattern: '^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d{0,2}0*$',
            title: 'Unit Price'
        },
        total_amount: {
            type: 'string',
            pattern: '^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d{0,2}0*$',
            title: 'Total Amount'
        },
        payment_method_id: {
            type: 'string',
            format: 'uuid',
            title: 'Payment Method Id'
        },
        customer_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Customer Name'
        },
        notes: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 1000
                },
                {
                    type: 'null'
                }
            ],
            title: 'Notes'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        sale_date: {
            type: 'string',
            format: 'date-time',
            title: 'Sale Date'
        },
        product: {
            '$ref': '#/components/schemas/ProductPublic'
        },
        payment_method: {
            '$ref': '#/components/schemas/PaymentMethodPublic'
        },
        voided: {
            type: 'boolean',
            title: 'Voided'
        }
    },
    type: 'object',
    required: ['product_id', 'quantity', 'unit_price', 'total_amount', 'payment_method_id', 'id', 'sale_date', 'product', 'payment_method', 'voided'],
    title: 'SalePublic'
} as const;

export const SalesPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/SalePublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'SalesPublic'
} as const;

export const StockEntriesPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/StockEntryPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'StockEntriesPublic'
} as const;

export const StockEntryCreateSchema = {
    properties: {
        product_id: {
            type: 'string',
            format: 'uuid',
            title: 'Product Id'
        },
        entry_date: {
            type: 'string',
            format: 'date-time',
            title: 'Entry Date'
        },
        opening_stock: {
            type: 'integer',
            minimum: 0,
            title: 'Opening Stock'
        },
        added_stock: {
            type: 'integer',
            minimum: 0,
            title: 'Added Stock',
            default: 0
        },
        total_stock: {
            type: 'integer',
            minimum: 0,
            title: 'Total Stock'
        },
        sales: {
            type: 'integer',
            minimum: 0,
            title: 'Sales',
            default: 0
        },
        closing_stock: {
            type: 'integer',
            minimum: 0,
            title: 'Closing Stock'
        },
        physical_count: {
            anyOf: [
                {
                    type: 'integer',
                    minimum: 0
                },
                {
                    type: 'null'
                }
            ],
            title: 'Physical Count'
        },
        variance: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Variance'
        },
        amount: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'string',
                    pattern: '^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d{0,2}0*$'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Amount'
        },
        notes: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 1000
                },
                {
                    type: 'null'
                }
            ],
            title: 'Notes'
        }
    },
    type: 'object',
    required: ['product_id', 'opening_stock', 'total_stock', 'closing_stock'],
    title: 'StockEntryCreate'
} as const;

export const StockEntryPublicSchema = {
    properties: {
        product_id: {
            type: 'string',
            format: 'uuid',
            title: 'Product Id'
        },
        entry_date: {
            type: 'string',
            format: 'date-time',
            title: 'Entry Date'
        },
        opening_stock: {
            type: 'integer',
            minimum: 0,
            title: 'Opening Stock'
        },
        added_stock: {
            type: 'integer',
            minimum: 0,
            title: 'Added Stock',
            default: 0
        },
        total_stock: {
            type: 'integer',
            minimum: 0,
            title: 'Total Stock'
        },
        sales: {
            type: 'integer',
            minimum: 0,
            title: 'Sales',
            default: 0
        },
        closing_stock: {
            type: 'integer',
            minimum: 0,
            title: 'Closing Stock'
        },
        physical_count: {
            anyOf: [
                {
                    type: 'integer',
                    minimum: 0
                },
                {
                    type: 'null'
                }
            ],
            title: 'Physical Count'
        },
        variance: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Variance'
        },
        amount: {
            anyOf: [
                {
                    type: 'string',
                    pattern: '^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d{0,2}0*$'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Amount'
        },
        notes: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 1000
                },
                {
                    type: 'null'
                }
            ],
            title: 'Notes'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        },
        product: {
            '$ref': '#/components/schemas/ProductPublic'
        }
    },
    type: 'object',
    required: ['product_id', 'opening_stock', 'total_stock', 'closing_stock', 'id', 'created_at', 'product'],
    title: 'StockEntryPublic'
} as const;

export const StockEntryUpdateSchema = {
    properties: {
        added_stock: {
            anyOf: [
                {
                    type: 'integer',
                    minimum: 0
                },
                {
                    type: 'null'
                }
            ],
            title: 'Added Stock'
        },
        sales: {
            anyOf: [
                {
                    type: 'integer',
                    minimum: 0
                },
                {
                    type: 'null'
                }
            ],
            title: 'Sales'
        },
        closing_stock: {
            anyOf: [
                {
                    type: 'integer',
                    minimum: 0
                },
                {
                    type: 'null'
                }
            ],
            title: 'Closing Stock'
        },
        physical_count: {
            anyOf: [
                {
                    type: 'integer',
                    minimum: 0
                },
                {
                    type: 'null'
                }
            ],
            title: 'Physical Count'
        },
        variance: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Variance'
        },
        amount: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'string',
                    pattern: '^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d{0,2}0*$'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Amount'
        },
        notes: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Notes'
        }
    },
    type: 'object',
    title: 'StockEntryUpdate'
} as const;

export const TokenSchema = {
    properties: {
        access_token: {
            type: 'string',
            title: 'Access Token'
        },
        token_type: {
            type: 'string',
            title: 'Token Type',
            default: 'bearer'
        }
    },
    type: 'object',
    required: ['access_token'],
    title: 'Token'
} as const;

export const UpdatePasswordSchema = {
    properties: {
        current_password: {
            type: 'string',
            maxLength: 40,
            minLength: 8,
            title: 'Current Password'
        },
        new_password: {
            type: 'string',
            maxLength: 40,
            minLength: 8,
            title: 'New Password'
        }
    },
    type: 'object',
    required: ['current_password', 'new_password'],
    title: 'UpdatePassword'
} as const;

export const UserCreateSchema = {
    properties: {
        email: {
            type: 'string',
            maxLength: 255,
            format: 'email',
            title: 'Email'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        },
        is_superuser: {
            type: 'boolean',
            title: 'Is Superuser',
            default: false
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        password: {
            type: 'string',
            maxLength: 40,
            minLength: 8,
            title: 'Password'
        }
    },
    type: 'object',
    required: ['email', 'password'],
    title: 'UserCreate'
} as const;

export const UserPublicSchema = {
    properties: {
        email: {
            type: 'string',
            maxLength: 255,
            format: 'email',
            title: 'Email'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        },
        is_superuser: {
            type: 'boolean',
            title: 'Is Superuser',
            default: false
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        }
    },
    type: 'object',
    required: ['email', 'id'],
    title: 'UserPublic'
} as const;

export const UserRegisterSchema = {
    properties: {
        email: {
            type: 'string',
            maxLength: 255,
            format: 'email',
            title: 'Email'
        },
        password: {
            type: 'string',
            maxLength: 40,
            minLength: 8,
            title: 'Password'
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        }
    },
    type: 'object',
    required: ['email', 'password'],
    title: 'UserRegister'
} as const;

export const UserUpdateSchema = {
    properties: {
        email: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    format: 'email'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Email'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        },
        is_superuser: {
            type: 'boolean',
            title: 'Is Superuser',
            default: false
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        password: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 40,
                    minLength: 8
                },
                {
                    type: 'null'
                }
            ],
            title: 'Password'
        }
    },
    type: 'object',
    title: 'UserUpdate'
} as const;

export const UserUpdateMeSchema = {
    properties: {
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        email: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    format: 'email'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Email'
        }
    },
    type: 'object',
    title: 'UserUpdateMe'
} as const;

export const UsersPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/UserPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'UsersPublic'
} as const;

export const ValidationErrorSchema = {
    properties: {
        loc: {
            items: {
                anyOf: [
                    {
                        type: 'string'
                    },
                    {
                        type: 'integer'
                    }
                ]
            },
            type: 'array',
            title: 'Location'
        },
        msg: {
            type: 'string',
            title: 'Message'
        },
        type: {
            type: 'string',
            title: 'Error Type'
        }
    },
    type: 'object',
    required: ['loc', 'msg', 'type'],
    title: 'ValidationError'
} as const;