// This file is auto-generated by @hey-api/openapi-ts

export type BalanceSheet = {
    assets: BalanceSheetAssets;
    liabilities: BalanceSheetLiabilities;
    equity: number;
};

export type BalanceSheetAssets = {
    inventory: number;
    cash_and_receivables: number;
    total: number;
};

export type BalanceSheetLiabilities = {
    expenses: number;
    total: number;
};

export type Body_bulk_import_upload_file = {
    file: (Blob | File);
};

export type Body_login_login_access_token = {
    grant_type?: (string | null);
    username: string;
    password: string;
    scope?: string;
    client_id?: (string | null);
    client_secret?: (string | null);
};

export type Body_media_upload_image = {
    file: (Blob | File);
};

/**
 * Final import request with options.
 */
export type BulkImportFinalRequest = {
    session_id: string;
    skip_errors?: boolean;
    duplicate_action?: string;
    tags?: Array<(string)>;
    notes?: (string | null);
};

/**
 * Final result of bulk import.
 */
export type BulkImportResult = {
    import_id: string;
    session_id: string;
    success_count: number;
    error_count: number;
    duplicate_count: number;
    total_processed: number;
    duration_seconds: number;
    imported_product_ids?: Array<(string)>;
    errors?: Array<{
        [key: string]: unknown;
    }>;
};

export type BulkImportSessionPublic = {
    filename: string;
    total_rows: number;
    valid_rows?: number;
    error_rows?: number;
    duplicate_rows?: number;
    imported_rows?: number;
    status?: string;
    column_mapping?: ({
    [key: string]: unknown;
} | null);
    import_options?: ({
    [key: string]: unknown;
} | null);
    duplicate_action?: string;
    id: string;
    created_at: string;
    completed_at?: (string | null);
    columns?: (Array<(string)> | null);
    auto_mapping?: ({
    [key: string]: (string);
} | null);
};

/**
 * Response for validation endpoint.
 */
export type BulkImportValidationResponse = {
    session_id: string;
    rows: Array<ImportRow>;
    total_count: number;
    valid_count: number;
    error_count: number;
    duplicate_count: number;
};

export type CashierBreakdown = {
    cashier_name: string;
    count: number;
    amount: number;
};

export type CashierVariancePublic = {
    till_shift_id: string;
    cashier_id: string;
    total_variance: string;
    variance_type: string;
    notes?: (string | null);
    id: string;
    cashier_name?: (string | null);
    shift_type?: (string | null);
    created_at: string;
};

export type CashierVariancesPublic = {
    data: Array<CashierVariancePublic>;
    count: number;
    total_shortage?: string;
    total_overage?: string;
};

/**
 * Request model for column mapping.
 */
export type ColumnMappingRequest = {
    session_id: string;
    column_mapping: {
        [key: string]: (string);
    };
    default_category_id?: (string | null);
    default_status_id?: (string | null);
};

/**
 * Response after column mapping with validation results.
 */
export type ColumnMappingResponse = {
    session_id: string;
    total_rows: number;
    valid_rows: number;
    error_rows: number;
    duplicate_rows: number;
    preview_rows: Array<ImportRow>;
};

/**
 * List of customers
 */
export type CustomersPublic = {
    data: Array<CustomerSummary>;
    count: number;
};

/**
 * Customer summary with aggregated data
 */
export type CustomerSummary = {
    name: string;
    tel: string;
    balance: number;
    last_sale_date?: (string | null);
};

export type DashboardStats = {
    current_month_revenue: number;
    previous_month_revenue: number;
    today_revenue: number;
    yesterday_revenue: number;
    current_month_expenses: number;
    previous_month_expenses: number;
    revenue_change_percent: number;
    daily_income_change_percent: number;
    expense_change_percent: number;
    net_profit: number;
    previous_net_profit: number;
    net_profit_change_percent: number;
    unpaid_debts_total: number;
    unpaid_debts_count: number;
};

/**
 * Create a new debt. Balance is calculated automatically from amount - amount_paid.
 */
export type DebtCreate = {
    customer_name: string;
    customer_contact?: (string | null);
    sale_id?: (string | null);
    amount: (number | string);
    amount_paid?: (number | string);
    debt_date?: (string | null);
    due_date?: (string | null);
    notes?: (string | null);
};

export type DebtPaymentCreate = {
    debt_id: string;
    amount: (number | string);
    payment_method_id: string;
    payment_date?: string;
    notes?: (string | null);
};

export type DebtPaymentPublic = {
    debt_id: string;
    amount: string;
    payment_method_id: string;
    payment_date?: string;
    notes?: (string | null);
    id: string;
    payment_method: PaymentMethodPublic;
};

export type DebtPaymentsPublic = {
    data: Array<DebtPaymentPublic>;
    count: number;
};

export type DebtPublic = {
    customer_name: string;
    customer_contact?: (string | null);
    sale_id?: (string | null);
    amount: string;
    amount_paid?: string;
    balance: string;
    debt_date?: string;
    due_date?: (string | null);
    status?: string;
    notes?: (string | null);
    id: string;
    sale?: (SalePublic | null);
};

export type DebtsPublic = {
    data: Array<DebtPublic>;
    count: number;
};

export type DebtUpdate = {
    customer_name?: (string | null);
    customer_contact?: (string | null);
    amount?: (number | string | null);
    amount_paid?: (number | string | null);
    due_date?: (string | null);
    status?: (string | null);
    notes?: (string | null);
};

export type ExpenseCategoriesPublic = {
    data: Array<ExpenseCategoryPublic>;
    count: number;
};

export type ExpenseCategoryCreate = {
    name: string;
    description?: (string | null);
};

export type ExpenseCategoryPublic = {
    name: string;
    description?: (string | null);
    id: string;
};

export type ExpenseCategoryUpdate = {
    name?: (string | null);
    description?: (string | null);
};

export type ExpenseCreate = {
    category_id: string;
    amount: (number | string);
    description: string;
    expense_date?: string;
    notes?: (string | null);
};

export type ExpensePublic = {
    category_id: string;
    amount: string;
    description: string;
    expense_date?: string;
    notes?: (string | null);
    id: string;
    category: ExpenseCategoryPublic;
    created_by: UserPublic;
    created_at: string;
    updated_at: string;
};

export type ExpensesPublic = {
    data: Array<ExpensePublic>;
    count: number;
};

export type ExpenseUpdate = {
    category_id?: (string | null);
    amount?: (number | string | null);
    description?: (string | null);
    expense_date?: (string | null);
    notes?: (string | null);
};

/**
 * Request to fix a specific row.
 */
export type FixRowRequest = {
    session_id: string;
    row_number: number;
    updated_data: {
        [key: string]: unknown;
    };
};

export type GRNCreate = {
    supplier_id: string;
    transporter_id?: (string | null);
    transaction_date?: string;
    goods_receipt_date?: string;
    shipping_address?: (string | null);
    delivery_number?: (string | null);
    delivery_date?: (string | null);
    consignment_number?: (string | null);
    consignment_date?: (string | null);
    batch_number?: (string | null);
    driver_name?: (string | null);
    vehicle_reg_number?: (string | null);
    department?: (string | null);
    section?: (string | null);
    currency?: string;
    total_amount?: (number | string);
    is_approved?: boolean;
    approved_at?: (string | null);
    approved_by_id?: (string | null);
    payment_type?: string;
    credit_terms?: (string | null);
    requires_approval?: boolean;
    creates_debt?: boolean;
    notes?: (string | null);
    items?: Array<GRNItemCreate>;
};

export type GRNItemCreate = {
    grn_id?: (string | null);
    product_id: string;
    order_quantity?: (number | string);
    pending_quantity?: (number | string);
    received_quantity: (number | string);
    lpo_number?: (string | null);
    ledger_account?: (string | null);
    is_promo?: boolean;
    unit_price?: (number | string | null);
    total_price?: (number | string | null);
    notes?: (string | null);
};

export type GRNItemPublic = {
    grn_id: string;
    product_id: string;
    order_quantity?: string;
    pending_quantity?: string;
    received_quantity: string;
    lpo_number?: (string | null);
    ledger_account?: (string | null);
    is_promo?: boolean;
    unit_price?: (string | null);
    total_price?: (string | null);
    notes?: (string | null);
    id: string;
    product_name?: (string | null);
    product_code?: (string | null);
};

export type GRNPublic = {
    supplier_id: string;
    transporter_id?: (string | null);
    transaction_date?: string;
    goods_receipt_date?: string;
    shipping_address?: (string | null);
    delivery_number?: (string | null);
    delivery_date?: (string | null);
    consignment_number?: (string | null);
    consignment_date?: (string | null);
    batch_number?: (string | null);
    driver_name?: (string | null);
    vehicle_reg_number?: (string | null);
    department?: (string | null);
    section?: (string | null);
    currency?: string;
    total_amount?: string;
    is_approved?: boolean;
    approved_at?: (string | null);
    approved_by_id?: (string | null);
    payment_type?: string;
    credit_terms?: (string | null);
    requires_approval?: boolean;
    creates_debt?: boolean;
    notes?: (string | null);
    id: string;
    grn_number: string;
    created_at: string;
    supplier_name?: (string | null);
    transporter_name?: (string | null);
    items_count?: number;
};

export type GRNPublicWithItems = {
    supplier_id: string;
    transporter_id?: (string | null);
    transaction_date?: string;
    goods_receipt_date?: string;
    shipping_address?: (string | null);
    delivery_number?: (string | null);
    delivery_date?: (string | null);
    consignment_number?: (string | null);
    consignment_date?: (string | null);
    batch_number?: (string | null);
    driver_name?: (string | null);
    vehicle_reg_number?: (string | null);
    department?: (string | null);
    section?: (string | null);
    currency?: string;
    total_amount?: string;
    is_approved?: boolean;
    approved_at?: (string | null);
    approved_by_id?: (string | null);
    payment_type?: string;
    credit_terms?: (string | null);
    requires_approval?: boolean;
    creates_debt?: boolean;
    notes?: (string | null);
    id: string;
    grn_number: string;
    created_at: string;
    supplier_name?: (string | null);
    transporter_name?: (string | null);
    items_count?: number;
    items?: Array<GRNItemPublic>;
};

export type GRNsPublic = {
    data: Array<GRNPublic>;
    count: number;
};

export type GRNUpdate = {
    supplier_id?: (string | null);
    transporter_id?: (string | null);
    transaction_date?: (string | null);
    goods_receipt_date?: (string | null);
    shipping_address?: (string | null);
    delivery_number?: (string | null);
    delivery_date?: (string | null);
    consignment_number?: (string | null);
    consignment_date?: (string | null);
    batch_number?: (string | null);
    driver_name?: (string | null);
    vehicle_reg_number?: (string | null);
    department?: (string | null);
    section?: (string | null);
    currency?: (string | null);
    total_amount?: (number | string | null);
    is_approved?: (boolean | null);
    notes?: (string | null);
};

export type HTTPValidationError = {
    detail?: Array<ValidationError>;
};

/**
 * Represents a single row in the bulk import.
 */
export type ImportRow = {
    row_number: number;
    data: {
        [key: string]: unknown;
    };
    mapped_data?: ({
    [key: string]: unknown;
} | null);
    errors?: Array<ValidationError>;
    warnings?: Array<(string)>;
    is_duplicate?: boolean;
    duplicate_product_id?: (string | null);
    status?: string;
};

export type MediaPublic = {
    file_path: string;
    file_name: string;
    mime_type?: (string | null);
    size: number;
    id: string;
    created_at: string;
    url?: (string | null);
};

export type Message = {
    message: string;
};

/**
 * Create a sale with multiple payment methods
 */
export type MultiPaymentSaleCreate = {
    product_id: string;
    quantity: number;
    unit_price: number;
    total_amount: number;
    customer_name?: (string | null);
    notes?: (string | null);
    payments: Array<PaymentData>;
};

export type NewPassword = {
    token: string;
    new_password: string;
};

export type NotificationPublic = {
    user_id: string;
    notification_type: string;
    title: string;
    message: string;
    priority?: string;
    is_read?: boolean;
    read_at?: (string | null);
    link_url?: (string | null);
    link_text?: (string | null);
    extra_data?: ({
    [key: string]: unknown;
} | null);
    expires_at?: (string | null);
    id: string;
    created_at: string;
};

export type NotificationsPublic = {
    data: Array<NotificationPublic>;
    count: number;
    unread_count?: number;
};

/**
 * Individual payment data
 */
export type PaymentData = {
    payment_method_id: string;
    amount: number;
    reference_number?: (string | null);
};

export type PaymentMethodBreakdown = {
    payment_method: string;
    count: number;
    amount: number;
};

export type PaymentMethodCreate = {
    name: string;
    description?: (string | null);
    is_active?: boolean;
};

export type PaymentMethodPublic = {
    name: string;
    description?: (string | null);
    is_active?: boolean;
    id: string;
};

export type PaymentMethodsPublic = {
    data: Array<PaymentMethodPublic>;
    count: number;
};

export type PaymentMethodUpdate = {
    name?: (string | null);
    description?: (string | null);
    is_active?: (boolean | null);
};

export type PrivateUserCreate = {
    email: string;
    password: string;
    full_name: string;
    is_verified?: boolean;
};

export type ProductCategoriesPublic = {
    data: Array<ProductCategoryPublic>;
    count: number;
};

export type ProductCategoryPublic = {
    name: string;
    description?: (string | null);
    id: string;
    created_at: string;
};

export type ProductCreate = {
    name: string;
    description?: (string | null);
    buying_price: (number | string);
    selling_price: (number | string);
    current_stock?: number;
    reorder_level?: (number | null);
    reorder_quantity?: (number | string | null);
    enable_reorder_alerts?: boolean;
    category_id: string;
    status_id: string;
    image_id?: (string | null);
};

export type ProductPublic = {
    name: string;
    description?: (string | null);
    buying_price: string;
    selling_price: string;
    current_stock?: number;
    reorder_level?: (number | null);
    reorder_quantity?: (string | null);
    enable_reorder_alerts?: boolean;
    category_id: string;
    status_id: string;
    image_id?: (string | null);
    id: string;
    created_at: string;
    category: ProductCategoryPublic;
    status: ProductStatusPublic;
    image: (MediaPublic | null);
};

export type ProductsPublic = {
    data: Array<ProductPublic>;
    count: number;
};

export type ProductStatusPublic = {
    name: string;
    description?: (string | null);
    id: string;
};

export type ProductUpdate = {
    name?: (string | null);
    description?: (string | null);
    buying_price?: (number | string | null);
    selling_price?: (number | string | null);
    current_stock?: (number | null);
    reorder_level?: (number | null);
    reorder_quantity?: (number | string | null);
    enable_reorder_alerts?: (boolean | null);
    category_id?: (string | null);
    status_id?: (string | null);
    image_id?: (string | null);
};

export type RefreshTokenRequest = {
    refresh_token: string;
};

export type ReminderLogPublic = {
    reminder_setting_id?: (string | null);
    user_id: string;
    sent_to_email: string;
    sent_at?: string;
    status: string;
    error_message?: (string | null);
    items_included?: number;
    subject_line?: (string | null);
    extra_data?: ({
    [key: string]: unknown;
} | null);
    id: string;
    created_at: string;
};

export type ReminderLogsPublic = {
    data: Array<ReminderLogPublic>;
    count: number;
};

export type ReminderSettingCreate = {
    user_id: string;
    reminder_type: string;
    is_enabled?: boolean;
    frequency: string;
    send_time?: string;
    send_days?: ({
    [key: string]: unknown;
} | null);
    filter_criteria?: ({
    [key: string]: unknown;
} | null);
};

export type ReminderSettingPublic = {
    user_id: string;
    reminder_type: string;
    is_enabled?: boolean;
    frequency: string;
    send_time?: string;
    send_days?: ({
    [key: string]: unknown;
} | null);
    filter_criteria?: ({
    [key: string]: unknown;
} | null);
    last_sent_at?: (string | null);
    next_send_at?: (string | null);
    id: string;
};

export type ReminderSettingsPublic = {
    data: Array<ReminderSettingPublic>;
    count: number;
};

export type ReminderSettingUpdate = {
    is_enabled?: (boolean | null);
    frequency?: (string | null);
    send_time?: (string | null);
    send_days?: ({
    [key: string]: unknown;
} | null);
    filter_criteria?: ({
    [key: string]: unknown;
} | null);
};

export type SaleCreate = {
    product_id: string;
    quantity: number;
    unit_price: (number | string);
    total_amount: (number | string);
    payment_method_id: string;
    customer_name?: (string | null);
    notes?: (string | null);
};

export type SalePaymentPublic = {
    sale_id: string;
    payment_method_id: string;
    amount: string;
    reference_number?: (string | null);
    id: string;
    payment_method: PaymentMethodPublic;
    created_at: string;
};

export type SalePublic = {
    product_id: string;
    quantity: number;
    unit_price: string;
    total_amount: string;
    payment_method_id: string;
    customer_name?: (string | null);
    notes?: (string | null);
    id: string;
    sale_date: string;
    product: ProductPublic;
    payment_method: PaymentMethodPublic;
    created_by: UserPublic;
    voided: boolean;
};

export type SalesPublic = {
    data: Array<SalePublic>;
    count: number;
};

export type SalesSummary = {
    total_sales: number;
    total_amount: number;
    total_items: number;
    average_sale: number;
    payment_method_breakdown: Array<PaymentMethodBreakdown>;
    cashier_breakdown: Array<CashierBreakdown>;
};

export type ShiftReconciliationCreate = {
    shift_date?: string;
    opening_cash_float?: (number | string);
    closing_cash_float?: (number | string);
    total_bottles_sold?: number;
    total_cans_sold?: number;
    total_wines_sold?: number;
    total_others_sold?: number;
    total_cash?: (number | string);
    total_mpesa?: (number | string);
    total_other_payments?: (number | string);
    total_credit?: (number | string);
    total_sales_amount?: (number | string);
    total_transactions?: number;
    expected_cash?: (number | string);
    actual_cash?: (number | string);
    cash_variance?: (number | string);
    items_with_variance?: number;
    notes?: (string | null);
    status?: string;
};

export type ShiftReconciliationPublic = {
    shift_date?: string;
    opening_cash_float?: string;
    closing_cash_float?: string;
    total_bottles_sold?: number;
    total_cans_sold?: number;
    total_wines_sold?: number;
    total_others_sold?: number;
    total_cash?: string;
    total_mpesa?: string;
    total_other_payments?: string;
    total_credit?: string;
    total_sales_amount?: string;
    total_transactions?: number;
    expected_cash?: string;
    actual_cash?: string;
    cash_variance?: string;
    items_with_variance?: number;
    notes?: (string | null);
    status?: string;
    id: string;
    created_at: string;
};

export type ShiftReconciliationsPublic = {
    data: Array<ShiftReconciliationPublic>;
    count: number;
};

export type ShiftReconciliationUpdate = {
    closing_cash_float?: (number | string | null);
    actual_cash?: (number | string | null);
    notes?: (string | null);
    status?: (string | null);
};

export type StockEntriesPublic = {
    data: Array<StockEntryPublic>;
    count: number;
};

export type StockEntryCreate = {
    product_id: string;
    entry_date?: string;
    opening_stock: number;
    added_stock?: number;
    total_stock: number;
    sales?: number;
    closing_stock: number;
    physical_count?: (number | null);
    variance?: (number | null);
    amount?: (number | string | null);
    notes?: (string | null);
};

export type StockEntryPublic = {
    product_id: string;
    entry_date?: string;
    opening_stock: number;
    added_stock?: number;
    total_stock: number;
    sales?: number;
    closing_stock: number;
    physical_count?: (number | null);
    variance?: (number | null);
    amount?: (string | null);
    notes?: (string | null);
    id: string;
    created_at: string;
    product: ProductPublic;
};

export type StockEntryUpdate = {
    added_stock?: (number | null);
    sales?: (number | null);
    closing_stock?: (number | null);
    physical_count?: (number | null);
    variance?: (number | null);
    amount?: (number | string | null);
    notes?: (string | null);
};

export type StockItem = {
    id: string;
    name: string;
    category: string;
    current_stock: number;
    buying_price: number;
    selling_price: number;
    inventory_value: number;
    reorder_level: number;
    status: string;
};

export type StockSummary = {
    total_products: number;
    total_inventory_value: number;
    low_stock_count: number;
    out_of_stock_count: number;
    products: Array<StockItem>;
};

export type SupplierCreate = {
    name: string;
    contact_person?: (string | null);
    email?: (string | null);
    phone?: (string | null);
    address?: (string | null);
    credit_limit?: (number | string);
    current_credit_used?: (number | string);
    is_active?: boolean;
};

export type SupplierDebtCreate = {
    supplier_id: string;
    grn_id: string;
    total_amount: (number | string);
    payment_terms: string;
    credit_period_days?: (number | null);
    invoice_number?: (string | null);
    invoice_date?: (string | null);
    due_date?: (string | null);
    currency?: string;
    notes?: (string | null);
};

export type SupplierDebtInstallmentCreate = {
    supplier_debt_id: string;
    installment_number: number;
    installment_amount: (number | string);
    due_date: string;
    notes?: (string | null);
};

export type SupplierDebtInstallmentPublic = {
    supplier_debt_id: string;
    installment_number: number;
    installment_amount: string;
    due_date: string;
    amount_paid?: string;
    balance: string;
    status?: string;
    notes?: (string | null);
    id: string;
};

export type SupplierDebtInstallmentsPublic = {
    data: Array<SupplierDebtInstallmentPublic>;
    count: number;
};

export type SupplierDebtPaymentCreate = {
    supplier_debt_id: string;
    installment_id?: (string | null);
    payment_amount: (number | string);
    payment_date?: string;
    payment_method_id: string;
    payment_reference?: (string | null);
    notes?: (string | null);
};

export type SupplierDebtPaymentPublic = {
    supplier_debt_id: string;
    installment_id?: (string | null);
    payment_amount: string;
    payment_date?: string;
    payment_method_id: string;
    payment_reference?: (string | null);
    notes?: (string | null);
    id: string;
    payment_method: PaymentMethodPublic;
};

export type SupplierDebtPublic = {
    supplier_id: string;
    grn_id: string;
    total_amount: string;
    amount_paid?: string;
    balance: string;
    payment_terms: string;
    credit_period_days?: (number | null);
    invoice_number?: (string | null);
    invoice_date?: string;
    due_date: string;
    status?: string;
    is_overdue?: boolean;
    days_overdue?: number;
    currency?: string;
    notes?: (string | null);
    id: string;
    created_at: string;
    supplier_name?: (string | null);
    grn_number?: (string | null);
};

export type SupplierDebtPublicWithDetails = {
    supplier_id: string;
    grn_id: string;
    total_amount: string;
    amount_paid?: string;
    balance: string;
    payment_terms: string;
    credit_period_days?: (number | null);
    invoice_number?: (string | null);
    invoice_date?: string;
    due_date: string;
    status?: string;
    is_overdue?: boolean;
    days_overdue?: number;
    currency?: string;
    notes?: (string | null);
    id: string;
    created_at: string;
    supplier_name?: (string | null);
    grn_number?: (string | null);
    installments?: Array<SupplierDebtInstallmentPublic>;
    payments?: Array<SupplierDebtPaymentPublic>;
};

export type SupplierDebtsPublic = {
    data: Array<SupplierDebtPublic>;
    count: number;
};

export type SupplierDebtUpdate = {
    payment_terms?: (string | null);
    invoice_number?: (string | null);
    due_date?: (string | null);
    status?: (string | null);
    notes?: (string | null);
};

export type SupplierPublic = {
    name: string;
    contact_person?: (string | null);
    email?: (string | null);
    phone?: (string | null);
    address?: (string | null);
    credit_limit?: string;
    current_credit_used?: string;
    is_active?: boolean;
    id: string;
    outstanding_debt?: (string | null);
};

export type SuppliersPublic = {
    data: Array<SupplierPublic>;
    count: number;
};

export type SupplierUpdate = {
    name?: (string | null);
    contact_person?: (string | null);
    email?: (string | null);
    phone?: (string | null);
    address?: (string | null);
    is_active?: (boolean | null);
};

/**
 * Create a new till shift
 */
export type TillShiftCreate = {
    shift_type: string;
    opening_cash_float: (number | string);
    opening_balance?: (number | string | null);
    notes?: (string | null);
};

/**
 * Public model for till shift
 */
export type TillShiftPublic = {
    shift_type: string;
    opening_cash_float: string;
    opening_balance?: (string | null);
    opening_time?: string;
    closing_time?: (string | null);
    closing_cash_float?: (string | null);
    status?: string;
    notes?: (string | null);
    id: string;
    opened_by_id: string;
    closed_by_id: (string | null);
    opened_by_name?: (string | null);
    closed_by_name?: (string | null);
    created_at: string;
    updated_at: string;
};

export type TillShiftsPublic = {
    data: Array<TillShiftPublic>;
    count: number;
};

export type Token = {
    access_token: string;
    refresh_token?: (string | null);
    token_type?: string;
};

export type TransporterCreate = {
    name: string;
    contact_person?: (string | null);
    phone?: (string | null);
    vehicle_registration?: (string | null);
    is_active?: boolean;
};

export type TransporterPublic = {
    name: string;
    contact_person?: (string | null);
    phone?: (string | null);
    vehicle_registration?: (string | null);
    is_active?: boolean;
    id: string;
};

export type TransportersPublic = {
    data: Array<TransporterPublic>;
    count: number;
};

export type TransporterUpdate = {
    name?: (string | null);
    contact_person?: (string | null);
    phone?: (string | null);
    vehicle_registration?: (string | null);
    is_active?: (boolean | null);
};

export type UpdatePassword = {
    current_password: string;
    new_password: string;
};

export type UserCreate = {
    email: string;
    username?: (string | null);
    is_active?: boolean;
    is_superuser?: boolean;
    is_auditor?: boolean;
    full_name?: (string | null);
    password: string;
};

export type UserPublic = {
    email: string;
    username?: (string | null);
    is_active?: boolean;
    is_superuser?: boolean;
    is_auditor?: boolean;
    full_name?: (string | null);
    id: string;
};

export type UserRegister = {
    email: string;
    username?: (string | null);
    password: string;
    full_name?: (string | null);
};

export type UsersPublic = {
    data: Array<UserPublic>;
    count: number;
};

export type UserUpdate = {
    email?: (string | null);
    username?: (string | null);
    is_active?: (boolean | null);
    is_superuser?: (boolean | null);
    is_auditor?: (boolean | null);
    full_name?: (string | null);
    password?: (string | null);
};

export type UserUpdateMe = {
    full_name?: (string | null);
    email?: (string | null);
    username?: (string | null);
};

export type ValidationError = {
    loc: Array<(string | number)>;
    msg: string;
    type: string;
};

export type AnalyticsGetSalesSummaryData = {
    /**
     * End date for summary
     */
    endDate?: (string | null);
    /**
     * Start date for summary
     */
    startDate?: (string | null);
};

export type AnalyticsGetSalesSummaryResponse = (SalesSummary);

export type AnalyticsGetStockSummaryResponse = (StockSummary);

export type AnalyticsGetBalanceSheetData = {
    /**
     * End date for balance sheet
     */
    endDate?: (string | null);
    /**
     * Start date for balance sheet
     */
    startDate?: (string | null);
};

export type AnalyticsGetBalanceSheetResponse = (BalanceSheet);

export type AnalyticsGetDashboardStatsResponse = (DashboardStats);

export type BulkImportDownloadTemplateResponse = (unknown);

export type BulkImportUploadFileData = {
    formData: Body_bulk_import_upload_file;
};

export type BulkImportUploadFileResponse = (BulkImportSessionPublic);

export type BulkImportMapColumnsData = {
    requestBody: ColumnMappingRequest;
};

export type BulkImportMapColumnsResponse = (ColumnMappingResponse);

export type BulkImportGetValidationResultsData = {
    filter?: (string | null);
    limit?: number;
    sessionId: string;
    skip?: number;
};

export type BulkImportGetValidationResultsResponse = (BulkImportValidationResponse);

export type BulkImportFixRowData = {
    requestBody: FixRowRequest;
    sessionId: string;
};

export type BulkImportFixRowResponse = (unknown);

export type BulkImportImportProductsData = {
    requestBody: BulkImportFinalRequest;
    sessionId: string;
};

export type BulkImportImportProductsResponse = (BulkImportResult);

export type BulkImportGetImportStatusData = {
    sessionId: string;
};

export type BulkImportGetImportStatusResponse = (BulkImportSessionPublic);

export type CustomersGetCustomersData = {
    limit?: number;
    /**
     * Search by name or tel
     */
    search?: (string | null);
    skip?: number;
};

export type CustomersGetCustomersResponse = (CustomersPublic);

export type DebtsReadDebtsData = {
    customerName?: (string | null);
    endDate?: (string | null);
    limit?: number;
    skip?: number;
    startDate?: (string | null);
    status?: (string | null);
};

export type DebtsReadDebtsResponse = (DebtsPublic);

export type DebtsCreateDebtData = {
    requestBody: DebtCreate;
};

export type DebtsCreateDebtResponse = (DebtPublic);

export type DebtsReadDebtData = {
    debtId: string;
};

export type DebtsReadDebtResponse = (DebtPublic);

export type DebtsUpdateDebtData = {
    debtId: string;
    requestBody: DebtUpdate;
};

export type DebtsUpdateDebtResponse = (DebtPublic);

export type DebtsDeleteDebtData = {
    debtId: string;
};

export type DebtsDeleteDebtResponse = (unknown);

export type DebtsCreateDebtPaymentData = {
    debtId: string;
    requestBody: DebtPaymentCreate;
};

export type DebtsCreateDebtPaymentResponse = (DebtPaymentPublic);

export type DebtsReadDebtPaymentsData = {
    debtId: string;
    limit?: number;
    skip?: number;
};

export type DebtsReadDebtPaymentsResponse = (DebtPaymentsPublic);

export type DebtsGetCustomerBalanceData = {
    customerName: string;
};

export type DebtsGetCustomerBalanceResponse = (unknown);

export type ExpensesReadExpenseCategoriesData = {
    limit?: number;
    skip?: number;
};

export type ExpensesReadExpenseCategoriesResponse = (ExpenseCategoriesPublic);

export type ExpensesCreateExpenseCategoryData = {
    requestBody: ExpenseCategoryCreate;
};

export type ExpensesCreateExpenseCategoryResponse = (ExpenseCategoryPublic);

export type ExpensesReadExpenseCategoryData = {
    categoryId: string;
};

export type ExpensesReadExpenseCategoryResponse = (ExpenseCategoryPublic);

export type ExpensesUpdateExpenseCategoryData = {
    categoryId: string;
    requestBody: ExpenseCategoryUpdate;
};

export type ExpensesUpdateExpenseCategoryResponse = (ExpenseCategoryPublic);

export type ExpensesDeleteExpenseCategoryData = {
    categoryId: string;
};

export type ExpensesDeleteExpenseCategoryResponse = (unknown);

export type ExpensesReadExpensesData = {
    categoryId?: (string | null);
    endDate?: (string | null);
    limit?: number;
    search?: (string | null);
    skip?: number;
    startDate?: (string | null);
};

export type ExpensesReadExpensesResponse = (ExpensesPublic);

export type ExpensesCreateExpenseData = {
    requestBody: ExpenseCreate;
};

export type ExpensesCreateExpenseResponse = (ExpensePublic);

export type ExpensesReadExpenseData = {
    expenseId: string;
};

export type ExpensesReadExpenseResponse = (ExpensePublic);

export type ExpensesUpdateExpenseData = {
    expenseId: string;
    requestBody: ExpenseUpdate;
};

export type ExpensesUpdateExpenseResponse = (ExpensePublic);

export type ExpensesDeleteExpenseData = {
    expenseId: string;
};

export type ExpensesDeleteExpenseResponse = (unknown);

export type ExpensesGetExpenseSummaryData = {
    categoryId?: (string | null);
    endDate?: (string | null);
    startDate?: (string | null);
};

export type ExpensesGetExpenseSummaryResponse = (unknown);

export type GrnReadSuppliersData = {
    isActive?: (boolean | null);
    limit?: number;
    search?: (string | null);
    skip?: number;
};

export type GrnReadSuppliersResponse = (SuppliersPublic);

export type GrnCreateSupplierData = {
    requestBody: SupplierCreate;
};

export type GrnCreateSupplierResponse = (SupplierPublic);

export type GrnReadSupplierData = {
    supplierId: string;
};

export type GrnReadSupplierResponse = (SupplierPublic);

export type GrnUpdateSupplierData = {
    requestBody: SupplierUpdate;
    supplierId: string;
};

export type GrnUpdateSupplierResponse = (SupplierPublic);

export type GrnDeleteSupplierData = {
    supplierId: string;
};

export type GrnDeleteSupplierResponse = (unknown);

export type GrnReadTransportersData = {
    isActive?: (boolean | null);
    limit?: number;
    search?: (string | null);
    skip?: number;
};

export type GrnReadTransportersResponse = (TransportersPublic);

export type GrnCreateTransporterData = {
    requestBody: TransporterCreate;
};

export type GrnCreateTransporterResponse = (TransporterPublic);

export type GrnReadTransporterData = {
    transporterId: string;
};

export type GrnReadTransporterResponse = (TransporterPublic);

export type GrnUpdateTransporterData = {
    requestBody: TransporterUpdate;
    transporterId: string;
};

export type GrnUpdateTransporterResponse = (TransporterPublic);

export type GrnDeleteTransporterData = {
    transporterId: string;
};

export type GrnDeleteTransporterResponse = (unknown);

export type GrnReadGrnsData = {
    endDate?: (string | null);
    isApproved?: (boolean | null);
    limit?: number;
    search?: (string | null);
    skip?: number;
    startDate?: (string | null);
    supplierId?: (string | null);
};

export type GrnReadGrnsResponse = (GRNsPublic);

export type GrnCreateGrnData = {
    requestBody: GRNCreate;
};

export type GrnCreateGrnResponse = (GRNPublicWithItems);

export type GrnReadGrnData = {
    grnId: string;
};

export type GrnReadGrnResponse = (GRNPublicWithItems);

export type GrnUpdateGrnData = {
    grnId: string;
    requestBody: GRNUpdate;
};

export type GrnUpdateGrnResponse = (GRNPublicWithItems);

export type GrnDeleteGrnData = {
    grnId: string;
};

export type GrnDeleteGrnResponse = (unknown);

export type GrnApproveGrnData = {
    grnId: string;
};

export type GrnApproveGrnResponse = (GRNPublicWithItems);

export type LoginLoginAccessTokenData = {
    formData: Body_login_login_access_token;
};

export type LoginLoginAccessTokenResponse = (Token);

export type LoginRefreshTokenData = {
    requestBody: RefreshTokenRequest;
};

export type LoginRefreshTokenResponse = (Token);

export type LoginRevokeRefreshTokenData = {
    requestBody: RefreshTokenRequest;
};

export type LoginRevokeRefreshTokenResponse = (Message);

export type LoginTestTokenResponse = (UserPublic);

export type LoginRecoverPasswordData = {
    email: string;
};

export type LoginRecoverPasswordResponse = (Message);

export type LoginResetPasswordData = {
    requestBody: NewPassword;
};

export type LoginResetPasswordResponse = (Message);

export type LoginRecoverPasswordHtmlContentData = {
    email: string;
};

export type LoginRecoverPasswordHtmlContentResponse = (string);

export type MediaUploadImageData = {
    formData: Body_media_upload_image;
};

export type MediaUploadImageResponse = (MediaPublic);

export type MediaServeImageData = {
    mediaId: string;
};

export type MediaServeImageResponse = (unknown);

export type MediaDeleteMediaData = {
    mediaId: string;
};

export type MediaDeleteMediaResponse = ({
    [key: string]: (string);
});

export type MediaListMediaData = {
    limit?: number;
    skip?: number;
};

export type MediaListMediaResponse = (Array<MediaPublic>);

export type NotificationsListNotificationsData = {
    isRead?: (boolean | null);
    limit?: number;
    notificationType?: (string | null);
    priority?: (string | null);
    skip?: number;
};

export type NotificationsListNotificationsResponse = (NotificationsPublic);

export type NotificationsGetUnreadCountResponse = ({
    [key: string]: (number);
});

export type NotificationsMarkAsReadData = {
    notificationId: string;
};

export type NotificationsMarkAsReadResponse = (NotificationPublic);

export type NotificationsMarkAllAsReadResponse = (Message);

export type NotificationsDeleteNotificationData = {
    notificationId: string;
};

export type NotificationsDeleteNotificationResponse = (Message);

export type NotificationsGetNotificationTypesResponse = ({
    [key: string]: Array<(string)>;
});

export type PrivateCreateUserData = {
    requestBody: PrivateUserCreate;
};

export type PrivateCreateUserResponse = (UserPublic);

export type ProductsReadCategoriesResponse = (ProductCategoriesPublic);

export type ProductsReadStatusesResponse = (Array<ProductStatusPublic>);

export type ProductsReadProductsData = {
    categoryId?: (string | null);
    limit?: number;
    name?: (string | null);
    skip?: number;
    statusId?: (string | null);
};

export type ProductsReadProductsResponse = (ProductsPublic);

export type ProductsCreateProductData = {
    requestBody: ProductCreate;
};

export type ProductsCreateProductResponse = (ProductPublic);

export type ProductsReadProductData = {
    id: string;
};

export type ProductsReadProductResponse = (ProductPublic);

export type ProductsUpdateProductData = {
    id: string;
    requestBody: ProductUpdate;
};

export type ProductsUpdateProductResponse = (ProductPublic);

export type ProductsDeleteProductData = {
    id: string;
};

export type ProductsDeleteProductResponse = ({
    [key: string]: (string);
});

export type RemindersListReminderSettingsResponse = (ReminderSettingsPublic);

export type RemindersCreateReminderSettingData = {
    requestBody: ReminderSettingCreate;
};

export type RemindersCreateReminderSettingResponse = (ReminderSettingPublic);

export type RemindersGetReminderSettingData = {
    settingId: string;
};

export type RemindersGetReminderSettingResponse = (ReminderSettingPublic);

export type RemindersUpdateReminderSettingData = {
    requestBody: ReminderSettingUpdate;
    settingId: string;
};

export type RemindersUpdateReminderSettingResponse = (ReminderSettingPublic);

export type RemindersDeleteReminderSettingData = {
    settingId: string;
};

export type RemindersDeleteReminderSettingResponse = (Message);

export type RemindersListReminderLogsData = {
    limit?: number;
    skip?: number;
    status?: (string | null);
};

export type RemindersListReminderLogsResponse = (ReminderLogsPublic);

export type RemindersGetReminderStatisticsResponse = ({
    [key: string]: unknown;
});

export type RemindersGetReminderTypesResponse = ({
    [key: string]: Array<(string)>;
});

export type SalesReadPaymentMethodsData = {
    limit?: number;
    skip?: number;
};

export type SalesReadPaymentMethodsResponse = (PaymentMethodsPublic);

export type SalesCreatePaymentMethodData = {
    requestBody: PaymentMethodCreate;
};

export type SalesCreatePaymentMethodResponse = (PaymentMethodPublic);

export type SalesUpdatePaymentMethodData = {
    paymentMethodId: string;
    requestBody: PaymentMethodUpdate;
};

export type SalesUpdatePaymentMethodResponse = (PaymentMethodPublic);

export type SalesSearchProductsForSaleData = {
    /**
     * Filter by category ID
     */
    categoryId?: (string | null);
    /**
     * Maximum results to return
     */
    limit?: number;
    /**
     * Search query
     */
    q: string;
};

export type SalesSearchProductsForSaleResponse = (Array<ProductPublic>);

export type SalesCreateSaleData = {
    requestBody: SaleCreate;
};

export type SalesCreateSaleResponse = (SalePublic);

export type SalesReadSalesData = {
    /**
     * Filter by cashier name (searches full_name and username)
     */
    cashierName?: (string | null);
    /**
     * Filter by product category
     */
    categoryId?: (string | null);
    /**
     * Filter sales until this date
     */
    endDate?: (string | null);
    /**
     * Exclude sales that have associated debts (for receipts view)
     */
    excludeWithDebt?: boolean;
    limit?: number;
    /**
     * Filter by payment method
     */
    paymentMethodId?: (string | null);
    /**
     * Filter by product ID
     */
    productId?: (string | null);
    /**
     * Search by receipt number (last 6 chars) or notes
     */
    search?: (string | null);
    skip?: number;
    /**
     * Filter sales from this date
     */
    startDate?: (string | null);
};

export type SalesReadSalesResponse = (SalesPublic);

export type SalesCreateSaleWithMultiplePaymentsData = {
    requestBody: MultiPaymentSaleCreate;
};

export type SalesCreateSaleWithMultiplePaymentsResponse = (SalePublic);

export type SalesReadSalePaymentsData = {
    saleId: string;
};

export type SalesReadSalePaymentsResponse = (Array<SalePaymentPublic>);

export type SalesGetTodaySalesSummaryResponse = ({
    [key: string]: unknown;
});

export type SalesReadSaleData = {
    saleId: string;
};

export type SalesReadSaleResponse = (SalePublic);

export type SalesDeleteSaleData = {
    saleId: string;
};

export type SalesDeleteSaleResponse = (unknown);

export type ShiftReconciliationCreateShiftReconciliationData = {
    requestBody: ShiftReconciliationCreate;
};

export type ShiftReconciliationCreateShiftReconciliationResponse = (ShiftReconciliationPublic);

export type ShiftReconciliationReadShiftReconciliationsData = {
    /**
     * Filter until this date
     */
    endDate?: (string | null);
    limit?: number;
    skip?: number;
    /**
     * Filter from this date
     */
    startDate?: (string | null);
};

export type ShiftReconciliationReadShiftReconciliationsResponse = (ShiftReconciliationsPublic);

export type ShiftReconciliationReadShiftReconciliationData = {
    shiftId: string;
};

export type ShiftReconciliationReadShiftReconciliationResponse = (ShiftReconciliationPublic);

export type ShiftReconciliationUpdateShiftReconciliationData = {
    requestBody: ShiftReconciliationUpdate;
    shiftId: string;
};

export type ShiftReconciliationUpdateShiftReconciliationResponse = (ShiftReconciliationPublic);

export type ShiftReconciliationGetCurrentCashSummaryData = {
    /**
     * End date (defaults to today)
     */
    endDate?: (string | null);
    /**
     * Start date (defaults to today)
     */
    startDate?: (string | null);
};

export type ShiftReconciliationGetCurrentCashSummaryResponse = ({
    [key: string]: unknown;
});

export type StockEntriesSearchProductsForStockEntryData = {
    /**
     * Maximum results to return
     */
    limit?: number;
    /**
     * Search query
     */
    q: string;
};

export type StockEntriesSearchProductsForStockEntryResponse = (Array<ProductPublic>);

export type StockEntriesReadStockEntriesData = {
    limit?: number;
    productId?: (string | null);
    skip?: number;
};

export type StockEntriesReadStockEntriesResponse = (StockEntriesPublic);

export type StockEntriesCreateStockEntryData = {
    requestBody: StockEntryCreate;
};

export type StockEntriesCreateStockEntryResponse = (StockEntryPublic);

export type StockEntriesReadStockEntryData = {
    id: string;
};

export type StockEntriesReadStockEntryResponse = (StockEntryPublic);

export type StockEntriesUpdateStockEntryData = {
    id: string;
    requestBody: StockEntryUpdate;
};

export type StockEntriesUpdateStockEntryResponse = (StockEntryPublic);

export type StockEntriesDeleteStockEntryData = {
    id: string;
};

export type StockEntriesDeleteStockEntryResponse = ({
    [key: string]: (string);
});

export type SupplierDebtsListSupplierDebtsData = {
    endDate?: (string | null);
    isOverdue?: (boolean | null);
    limit?: number;
    skip?: number;
    startDate?: (string | null);
    status?: (string | null);
    supplierId?: (string | null);
};

export type SupplierDebtsListSupplierDebtsResponse = (SupplierDebtsPublic);

export type SupplierDebtsCreateSupplierDebtData = {
    requestBody: SupplierDebtCreate;
};

export type SupplierDebtsCreateSupplierDebtResponse = (SupplierDebtPublic);

export type SupplierDebtsGetSummaryResponse = ({
    [key: string]: unknown;
});

export type SupplierDebtsGetAgingReportData = {
    supplierId?: (string | null);
};

export type SupplierDebtsGetAgingReportResponse = (Array<{
    [key: string]: unknown;
}>);

export type SupplierDebtsGetSupplierDebtData = {
    debtId: string;
};

export type SupplierDebtsGetSupplierDebtResponse = (SupplierDebtPublicWithDetails);

export type SupplierDebtsUpdateSupplierDebtData = {
    debtId: string;
    requestBody: SupplierDebtUpdate;
};

export type SupplierDebtsUpdateSupplierDebtResponse = (SupplierDebtPublic);

export type SupplierDebtsRecordPaymentData = {
    debtId: string;
    requestBody: SupplierDebtPaymentCreate;
};

export type SupplierDebtsRecordPaymentResponse = (SupplierDebtPaymentPublic);

export type SupplierDebtsListInstallmentsData = {
    debtId: string;
};

export type SupplierDebtsListInstallmentsResponse = (SupplierDebtInstallmentsPublic);

export type SupplierDebtsCreateInstallmentsData = {
    debtId: string;
    requestBody: Array<SupplierDebtInstallmentCreate>;
};

export type SupplierDebtsCreateInstallmentsResponse = (SupplierDebtInstallmentsPublic);

export type TillOpenTillData = {
    requestBody: TillShiftCreate;
};

export type TillOpenTillResponse = (TillShiftPublic);

export type TillGetCurrentTillResponse = (TillShiftPublic);

export type TillGetTillStatusResponse = ({
    [key: string]: unknown;
});

export type TillCloseTillData = {
    /**
     * Closing cash float amount
     */
    closingCashFloat: (number | string);
};

export type TillCloseTillResponse = (TillShiftPublic);

export type TillGetSystemCountsResponse = ({
    [key: string]: unknown;
});

export type TillReconcileShiftData = {
    notes?: (string | null);
    requestBody: {
        [key: string]: unknown;
    };
};

export type TillReconcileShiftResponse = ({
    [key: string]: unknown;
});

export type TillGetCashierVariancesData = {
    /**
     * Filter by cashier ID
     */
    cashierId?: (string | null);
    /**
     * Filter until this date
     */
    endDate?: (string | null);
    limit?: number;
    skip?: number;
    /**
     * Filter from this date
     */
    startDate?: (string | null);
};

export type TillGetCashierVariancesResponse = (CashierVariancesPublic);

export type TillGetTillShiftsData = {
    limit?: number;
    skip?: number;
    /**
     * Filter by status: open, closed, reconciled
     */
    status?: (string | null);
};

export type TillGetTillShiftsResponse = (TillShiftsPublic);

export type UsersReadUsersData = {
    limit?: number;
    skip?: number;
};

export type UsersReadUsersResponse = (UsersPublic);

export type UsersCreateUserData = {
    requestBody: UserCreate;
};

export type UsersCreateUserResponse = (UserPublic);

export type UsersReadUserMeResponse = (UserPublic);

export type UsersDeleteUserMeResponse = (Message);

export type UsersUpdateUserMeData = {
    requestBody: UserUpdateMe;
};

export type UsersUpdateUserMeResponse = (UserPublic);

export type UsersUpdatePasswordMeData = {
    requestBody: UpdatePassword;
};

export type UsersUpdatePasswordMeResponse = (Message);

export type UsersRegisterUserData = {
    requestBody: UserRegister;
};

export type UsersRegisterUserResponse = (UserPublic);

export type UsersReadUserByIdData = {
    userId: string;
};

export type UsersReadUserByIdResponse = (UserPublic);

export type UsersUpdateUserData = {
    requestBody: UserUpdate;
    userId: string;
};

export type UsersUpdateUserResponse = (UserPublic);

export type UsersDeleteUserData = {
    userId: string;
};

export type UsersDeleteUserResponse = (Message);

export type UtilsTestEmailData = {
    emailTo: string;
};

export type UtilsTestEmailResponse = (Message);

export type UtilsHealthCheckResponse = (boolean);