// This file is auto-generated by @hey-api/openapi-ts

export type Body_login_login_access_token = {
    grant_type?: (string | null);
    username: string;
    password: string;
    scope?: string;
    client_id?: (string | null);
    client_secret?: (string | null);
};

export type Body_media_upload_image = {
    file: (Blob | File);
};

export type HTTPValidationError = {
    detail?: Array<ValidationError>;
};

export type MediaPublic = {
    file_name: string;
    file_path: string;
    mime_type?: (string | null);
    size: number;
    id: string;
    created_at: string;
    url: string;
};

export type Message = {
    message: string;
};

export type NewPassword = {
    token: string;
    new_password: string;
};

export type PrivateUserCreate = {
    email: string;
    password: string;
    full_name: string;
    is_verified?: boolean;
};

export type ProductCategoriesPublic = {
    data: Array<ProductCategoryPublic>;
    count: number;
};

export type ProductCategoryPublic = {
    name: string;
    description?: (string | null);
    id: string;
    created_at: string;
};

export type ProductCreate = {
    name: string;
    description?: (string | null);
    buying_price: (number | string);
    selling_price: (number | string);
    current_stock?: number;
    reorder_level?: (number | null);
    category_id: string;
    status_id: string;
    tag_id: string;
    image_id?: (string | null);
};

export type ProductPublic = {
    name: string;
    description?: (string | null);
    buying_price: string;
    selling_price: string;
    current_stock?: number;
    reorder_level?: (number | null);
    category_id: string;
    status_id: string;
    tag_id: string;
    image_id?: (string | null);
    id: string;
    created_at: string;
    category: ProductCategoryPublic;
    status: ProductStatusPublic;
    tag: ProductTagPublic;
    image: (MediaPublic | null);
};

export type ProductsPublic = {
    data: Array<ProductPublic>;
    count: number;
};

export type ProductStatusPublic = {
    name: string;
    description?: (string | null);
    id: string;
};

export type ProductTagPublic = {
    name: string;
    description?: (string | null);
    id: string;
    created_at: string;
};

export type ProductUpdate = {
    name?: (string | null);
    description?: (string | null);
    buying_price?: (number | string | null);
    selling_price?: (number | string | null);
    current_stock?: (number | null);
    reorder_level?: (number | null);
    category_id?: (string | null);
    status_id?: (string | null);
    tag_id?: (string | null);
    image_id?: (string | null);
};

export type Token = {
    access_token: string;
    token_type?: string;
};

export type UpdatePassword = {
    current_password: string;
    new_password: string;
};

export type UserCreate = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    password: string;
};

export type UserPublic = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    id: string;
};

export type UserRegister = {
    email: string;
    password: string;
    full_name?: (string | null);
};

export type UsersPublic = {
    data: Array<UserPublic>;
    count: number;
};

export type UserUpdate = {
    email?: (string | null);
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    password?: (string | null);
};

export type UserUpdateMe = {
    full_name?: (string | null);
    email?: (string | null);
};

export type ValidationError = {
    loc: Array<(string | number)>;
    msg: string;
    type: string;
};

export type LoginLoginAccessTokenData = {
    formData: Body_login_login_access_token;
};

export type LoginLoginAccessTokenResponse = (Token);

export type LoginTestTokenResponse = (UserPublic);

export type LoginRecoverPasswordData = {
    email: string;
};

export type LoginRecoverPasswordResponse = (Message);

export type LoginResetPasswordData = {
    requestBody: NewPassword;
};

export type LoginResetPasswordResponse = (Message);

export type LoginRecoverPasswordHtmlContentData = {
    email: string;
};

export type LoginRecoverPasswordHtmlContentResponse = (string);

export type MediaUploadImageData = {
    formData: Body_media_upload_image;
};

export type MediaUploadImageResponse = (MediaPublic);

export type MediaServeImageData = {
    mediaId: string;
};

export type MediaServeImageResponse = (unknown);

export type MediaDeleteMediaData = {
    mediaId: string;
};

export type MediaDeleteMediaResponse = ({
    [key: string]: (string);
});

export type MediaListMediaData = {
    limit?: number;
    skip?: number;
};

export type MediaListMediaResponse = (Array<MediaPublic>);

export type PrivateCreateUserData = {
    requestBody: PrivateUserCreate;
};

export type PrivateCreateUserResponse = (UserPublic);

export type ProductsReadCategoriesResponse = (ProductCategoriesPublic);

export type ProductsReadStatusesResponse = (Array<ProductStatusPublic>);

export type ProductsReadTagsResponse = (Array<ProductTagPublic>);

export type ProductsReadProductsData = {
    limit?: number;
    skip?: number;
};

export type ProductsReadProductsResponse = (ProductsPublic);

export type ProductsCreateProductData = {
    requestBody: ProductCreate;
};

export type ProductsCreateProductResponse = (ProductPublic);

export type ProductsReadProductData = {
    id: number;
};

export type ProductsReadProductResponse = (ProductPublic);

export type ProductsUpdateProductData = {
    id: number;
    requestBody: ProductUpdate;
};

export type ProductsUpdateProductResponse = (ProductPublic);

export type ProductsDeleteProductData = {
    id: number;
};

export type ProductsDeleteProductResponse = ({
    [key: string]: (string);
});

export type UsersReadUsersData = {
    limit?: number;
    skip?: number;
};

export type UsersReadUsersResponse = (UsersPublic);

export type UsersCreateUserData = {
    requestBody: UserCreate;
};

export type UsersCreateUserResponse = (UserPublic);

export type UsersReadUserMeResponse = (UserPublic);

export type UsersDeleteUserMeResponse = (Message);

export type UsersUpdateUserMeData = {
    requestBody: UserUpdateMe;
};

export type UsersUpdateUserMeResponse = (UserPublic);

export type UsersUpdatePasswordMeData = {
    requestBody: UpdatePassword;
};

export type UsersUpdatePasswordMeResponse = (Message);

export type UsersRegisterUserData = {
    requestBody: UserRegister;
};

export type UsersRegisterUserResponse = (UserPublic);

export type UsersReadUserByIdData = {
    userId: string;
};

export type UsersReadUserByIdResponse = (UserPublic);

export type UsersUpdateUserData = {
    requestBody: UserUpdate;
    userId: string;
};

export type UsersUpdateUserResponse = (UserPublic);

export type UsersDeleteUserData = {
    userId: string;
};

export type UsersDeleteUserResponse = (Message);

export type UtilsTestEmailData = {
    emailTo: string;
};

export type UtilsTestEmailResponse = (Message);

export type UtilsHealthCheckResponse = (boolean);