// This file is auto-generated by @hey-api/openapi-ts

export type BalanceSheet = {
    assets: BalanceSheetAssets;
    liabilities: BalanceSheetLiabilities;
    equity: number;
};

export type BalanceSheetAssets = {
    inventory: number;
    cash_and_receivables: number;
    total: number;
};

export type BalanceSheetLiabilities = {
    expenses: number;
    total: number;
};

export type Body_bulk_import_upload_file = {
    file: (Blob | File);
};

export type Body_login_login_access_token = {
    grant_type?: (string | null);
    username: string;
    password: string;
    scope?: string;
    client_id?: (string | null);
    client_secret?: (string | null);
};

export type Body_media_upload_image = {
    file: (Blob | File);
};

/**
 * Final import request with options.
 */
export type BulkImportFinalRequest = {
    session_id: string;
    skip_errors?: boolean;
    duplicate_action?: string;
    tags?: Array<(string)>;
    notes?: (string | null);
};

/**
 * Final result of bulk import.
 */
export type BulkImportResult = {
    import_id: string;
    session_id: string;
    success_count: number;
    error_count: number;
    duplicate_count: number;
    total_processed: number;
    duration_seconds: number;
    imported_product_ids?: Array<(string)>;
    errors?: Array<{
        [key: string]: unknown;
    }>;
};

export type BulkImportSessionPublic = {
    filename: string;
    total_rows: number;
    valid_rows?: number;
    error_rows?: number;
    duplicate_rows?: number;
    imported_rows?: number;
    status?: string;
    column_mapping?: ({
    [key: string]: unknown;
} | null);
    import_options?: ({
    [key: string]: unknown;
} | null);
    duplicate_action?: string;
    id: string;
    created_at: string;
    completed_at?: (string | null);
    columns?: (Array<(string)> | null);
    auto_mapping?: ({
    [key: string]: unknown;
} | null);
};

/**
 * Response for validation endpoint.
 */
export type BulkImportValidationResponse = {
    session_id: string;
    rows: Array<ImportRow>;
    total_count: number;
    valid_count: number;
    error_count: number;
    duplicate_count: number;
};

export type CashierBreakdown = {
    cashier_name: string;
    count: number;
    amount: number;
};

/**
 * Request model for column mapping.
 */
export type ColumnMappingRequest = {
    session_id: string;
    column_mapping: {
        [key: string]: unknown;
    };
    default_category_id?: (string | null);
    default_status_id?: (string | null);
};

/**
 * Response after column mapping with validation results.
 */
export type ColumnMappingResponse = {
    session_id: string;
    total_rows: number;
    valid_rows: number;
    error_rows: number;
    duplicate_rows: number;
    preview_rows: Array<ImportRow>;
};

/**
 * List of customers
 */
export type CustomersPublic = {
    data: Array<CustomerSummary>;
    count: number;
};

/**
 * Customer summary with aggregated data
 */
export type CustomerSummary = {
    name: string;
    tel: string;
    balance: number;
    last_sale_date?: (string | null);
};

export type DashboardStats = {
    current_month_revenue: number;
    previous_month_revenue: number;
    today_revenue: number;
    yesterday_revenue: number;
    current_month_expenses: number;
    previous_month_expenses: number;
    revenue_change_percent: number;
    daily_income_change_percent: number;
    expense_change_percent: number;
    net_profit: number;
    previous_net_profit: number;
    net_profit_change_percent: number;
};

export type DebtCreate = {
    customer_name: string;
    customer_contact?: (string | null);
    sale_id?: (string | null);
    amount: (number | string);
    amount_paid?: (number | string);
    balance: (number | string);
    debt_date?: string;
    due_date?: (string | null);
    status?: string;
    notes?: (string | null);
};

export type DebtPaymentCreate = {
    debt_id: string;
    amount: (number | string);
    payment_method_id: string;
    payment_date?: string;
    notes?: (string | null);
};

export type DebtPaymentPublic = {
    debt_id: string;
    amount: string;
    payment_method_id: string;
    payment_date?: string;
    notes?: (string | null);
    id: string;
    payment_method: PaymentMethodPublic;
};

export type DebtPaymentsPublic = {
    data: Array<DebtPaymentPublic>;
    count: number;
};

export type DebtPublic = {
    customer_name: string;
    customer_contact?: (string | null);
    sale_id?: (string | null);
    amount: string;
    amount_paid?: string;
    balance: string;
    debt_date?: string;
    due_date?: (string | null);
    status?: string;
    notes?: (string | null);
    id: string;
};

export type DebtsPublic = {
    data: Array<DebtPublic>;
    count: number;
};

export type DebtUpdate = {
    customer_name?: (string | null);
    customer_contact?: (string | null);
    amount?: (number | string | null);
    amount_paid?: (number | string | null);
    due_date?: (string | null);
    status?: (string | null);
    notes?: (string | null);
};

export type ExpenseCategoriesPublic = {
    data: Array<ExpenseCategoryPublic>;
    count: number;
};

export type ExpenseCategoryCreate = {
    name: string;
    description?: (string | null);
};

export type ExpenseCategoryPublic = {
    name: string;
    description?: (string | null);
    id: string;
};

export type ExpenseCategoryUpdate = {
    name?: (string | null);
    description?: (string | null);
};

export type ExpenseCreate = {
    category_id: string;
    amount: (number | string);
    description: string;
    expense_date?: string;
    notes?: (string | null);
};

export type ExpensePublic = {
    category_id: string;
    amount: string;
    description: string;
    expense_date?: string;
    notes?: (string | null);
    id: string;
    category: ExpenseCategoryPublic;
    created_by: UserPublic;
    created_at: string;
    updated_at: string;
};

export type ExpensesPublic = {
    data: Array<ExpensePublic>;
    count: number;
};

export type ExpenseUpdate = {
    category_id?: (string | null);
    amount?: (number | string | null);
    description?: (string | null);
    expense_date?: (string | null);
    notes?: (string | null);
};

/**
 * Request to fix a specific row.
 */
export type FixRowRequest = {
    session_id: string;
    row_number: number;
    updated_data: {
        [key: string]: unknown;
    };
};

export type HTTPValidationError = {
    detail?: Array<ValidationError>;
};

/**
 * Represents a single row in the bulk import.
 */
export type ImportRow = {
    row_number: number;
    data: {
        [key: string]: unknown;
    };
    mapped_data?: ({
    [key: string]: unknown;
} | null);
    errors?: Array<ValidationError>;
    warnings?: Array<(string)>;
    is_duplicate?: boolean;
    duplicate_product_id?: (string | null);
    status?: string;
};

export type MediaPublic = {
    file_path: string;
    file_name: string;
    mime_type?: (string | null);
    size: number;
    id: string;
    created_at: string;
    url?: (string | null);
};

export type Message = {
    message: string;
};

/**
 * Create a sale with multiple payment methods
 */
export type MultiPaymentSaleCreate = {
    product_id: string;
    quantity: number;
    unit_price: number;
    total_amount: number;
    customer_name?: (string | null);
    notes?: (string | null);
    payments: Array<PaymentData>;
};

export type NewPassword = {
    token: string;
    new_password: string;
};

/**
 * Individual payment data
 */
export type PaymentData = {
    payment_method_id: string;
    amount: number;
    reference_number?: (string | null);
};

export type PaymentMethodBreakdown = {
    payment_method: string;
    count: number;
    amount: number;
};

export type PaymentMethodCreate = {
    name: string;
    description?: (string | null);
    is_active?: boolean;
};

export type PaymentMethodPublic = {
    name: string;
    description?: (string | null);
    is_active?: boolean;
    id: string;
};

export type PaymentMethodsPublic = {
    data: Array<PaymentMethodPublic>;
    count: number;
};

export type PaymentMethodUpdate = {
    name?: (string | null);
    description?: (string | null);
    is_active?: (boolean | null);
};

export type PrivateUserCreate = {
    email: string;
    password: string;
    full_name: string;
    is_verified?: boolean;
};

export type ProductCategoriesPublic = {
    data: Array<ProductCategoryPublic>;
    count: number;
};

export type ProductCategoryPublic = {
    name: string;
    description?: (string | null);
    id: string;
    created_at: string;
};

export type ProductCreate = {
    name: string;
    description?: (string | null);
    buying_price: (number | string);
    selling_price: (number | string);
    current_stock?: number;
    reorder_level?: (number | null);
    category_id: string;
    status_id: string;
    image_id?: (string | null);
};

export type ProductPublic = {
    name: string;
    description?: (string | null);
    buying_price: string;
    selling_price: string;
    current_stock?: number;
    reorder_level?: (number | null);
    category_id: string;
    status_id: string;
    image_id?: (string | null);
    id: string;
    created_at: string;
    category: ProductCategoryPublic;
    status: ProductStatusPublic;
    image: (MediaPublic | null);
};

export type ProductsPublic = {
    data: Array<ProductPublic>;
    count: number;
};

export type ProductStatusPublic = {
    name: string;
    description?: (string | null);
    id: string;
};

export type ProductUpdate = {
    name?: (string | null);
    description?: (string | null);
    buying_price?: (number | string | null);
    selling_price?: (number | string | null);
    current_stock?: (number | null);
    reorder_level?: (number | null);
    category_id?: (string | null);
    status_id?: (string | null);
    image_id?: (string | null);
};

export type SaleCreate = {
    product_id: string;
    quantity: number;
    unit_price: (number | string);
    total_amount: (number | string);
    payment_method_id: string;
    customer_name?: (string | null);
    notes?: (string | null);
};

export type SalePaymentPublic = {
    sale_id: string;
    payment_method_id: string;
    amount: string;
    reference_number?: (string | null);
    id: string;
    payment_method: PaymentMethodPublic;
    created_at: string;
};

export type SalePublic = {
    product_id: string;
    quantity: number;
    unit_price: string;
    total_amount: string;
    payment_method_id: string;
    customer_name?: (string | null);
    notes?: (string | null);
    id: string;
    sale_date: string;
    product: ProductPublic;
    payment_method: PaymentMethodPublic;
    created_by: UserPublic;
    voided: boolean;
};

export type SalesPublic = {
    data: Array<SalePublic>;
    count: number;
};

export type SalesSummary = {
    total_sales: number;
    total_amount: number;
    total_items: number;
    average_sale: number;
    payment_method_breakdown: Array<PaymentMethodBreakdown>;
    cashier_breakdown: Array<CashierBreakdown>;
};

export type ShiftReconciliationCreate = {
    shift_date?: string;
    opening_cash_float?: (number | string);
    closing_cash_float?: (number | string);
    total_bottles_sold?: number;
    total_cans_sold?: number;
    total_wines_sold?: number;
    total_others_sold?: number;
    total_cash?: (number | string);
    total_mpesa?: (number | string);
    total_other_payments?: (number | string);
    total_credit?: (number | string);
    total_sales_amount?: (number | string);
    total_transactions?: number;
    expected_cash?: (number | string);
    actual_cash?: (number | string);
    cash_variance?: (number | string);
    items_with_variance?: number;
    notes?: (string | null);
    status?: string;
};

export type ShiftReconciliationPublic = {
    shift_date?: string;
    opening_cash_float?: string;
    closing_cash_float?: string;
    total_bottles_sold?: number;
    total_cans_sold?: number;
    total_wines_sold?: number;
    total_others_sold?: number;
    total_cash?: string;
    total_mpesa?: string;
    total_other_payments?: string;
    total_credit?: string;
    total_sales_amount?: string;
    total_transactions?: number;
    expected_cash?: string;
    actual_cash?: string;
    cash_variance?: string;
    items_with_variance?: number;
    notes?: (string | null);
    status?: string;
    id: string;
    created_at: string;
};

export type ShiftReconciliationsPublic = {
    data: Array<ShiftReconciliationPublic>;
    count: number;
};

export type ShiftReconciliationUpdate = {
    closing_cash_float?: (number | string | null);
    actual_cash?: (number | string | null);
    notes?: (string | null);
    status?: (string | null);
};

export type StockEntriesPublic = {
    data: Array<StockEntryPublic>;
    count: number;
};

export type StockEntryCreate = {
    product_id: string;
    entry_date?: string;
    opening_stock: number;
    added_stock?: number;
    total_stock: number;
    sales?: number;
    closing_stock: number;
    physical_count?: (number | null);
    variance?: (number | null);
    amount?: (number | string | null);
    notes?: (string | null);
};

export type StockEntryPublic = {
    product_id: string;
    entry_date?: string;
    opening_stock: number;
    added_stock?: number;
    total_stock: number;
    sales?: number;
    closing_stock: number;
    physical_count?: (number | null);
    variance?: (number | null);
    amount?: (string | null);
    notes?: (string | null);
    id: string;
    created_at: string;
    product: ProductPublic;
};

export type StockEntryUpdate = {
    added_stock?: (number | null);
    sales?: (number | null);
    closing_stock?: (number | null);
    physical_count?: (number | null);
    variance?: (number | null);
    amount?: (number | string | null);
    notes?: (string | null);
};

export type StockItem = {
    id: string;
    name: string;
    category: string;
    current_stock: number;
    buying_price: number;
    selling_price: number;
    inventory_value: number;
    reorder_level: number;
    status: string;
};

export type StockSummary = {
    total_products: number;
    total_inventory_value: number;
    low_stock_count: number;
    out_of_stock_count: number;
    products: Array<StockItem>;
};

export type Token = {
    access_token: string;
    token_type?: string;
};

export type UpdatePassword = {
    current_password: string;
    new_password: string;
};

export type UserCreate = {
    email: string;
    username?: (string | null);
    is_active?: boolean;
    is_superuser?: boolean;
    is_auditor?: boolean;
    full_name?: (string | null);
    password: string;
};

export type UserPublic = {
    email: string;
    username?: (string | null);
    is_active?: boolean;
    is_superuser?: boolean;
    is_auditor?: boolean;
    full_name?: (string | null);
    id: string;
};

export type UserRegister = {
    email: string;
    username?: (string | null);
    password: string;
    full_name?: (string | null);
};

export type UsersPublic = {
    data: Array<UserPublic>;
    count: number;
};

export type UserUpdate = {
    email?: (string | null);
    username?: (string | null);
    is_active?: (boolean | null);
    is_superuser?: (boolean | null);
    is_auditor?: (boolean | null);
    full_name?: (string | null);
    password?: (string | null);
};

export type UserUpdateMe = {
    full_name?: (string | null);
    email?: (string | null);
    username?: (string | null);
};

export type ValidationError = {
    loc: Array<(string | number)>;
    msg: string;
    type: string;
};

export type AnalyticsGetSalesSummaryData = {
    /**
     * End date for summary
     */
    endDate?: (string | null);
    /**
     * Start date for summary
     */
    startDate?: (string | null);
};

export type AnalyticsGetSalesSummaryResponse = (SalesSummary);

export type AnalyticsGetStockSummaryResponse = (StockSummary);

export type AnalyticsGetBalanceSheetData = {
    /**
     * End date for balance sheet
     */
    endDate?: (string | null);
    /**
     * Start date for balance sheet
     */
    startDate?: (string | null);
};

export type AnalyticsGetBalanceSheetResponse = (BalanceSheet);

export type AnalyticsGetDashboardStatsResponse = (DashboardStats);

export type BulkImportDownloadTemplateResponse = (unknown);

export type BulkImportUploadFileData = {
    formData: Body_bulk_import_upload_file;
};

export type BulkImportUploadFileResponse = (BulkImportSessionPublic);

export type BulkImportMapColumnsData = {
    requestBody: ColumnMappingRequest;
};

export type BulkImportMapColumnsResponse = (ColumnMappingResponse);

export type BulkImportGetValidationResultsData = {
    filter?: (string | null);
    limit?: number;
    sessionId: string;
    skip?: number;
};

export type BulkImportGetValidationResultsResponse = (BulkImportValidationResponse);

export type BulkImportFixRowData = {
    requestBody: FixRowRequest;
    sessionId: string;
};

export type BulkImportFixRowResponse = (unknown);

export type BulkImportImportProductsData = {
    requestBody: BulkImportFinalRequest;
    sessionId: string;
};

export type BulkImportImportProductsResponse = (BulkImportResult);

export type BulkImportGetImportStatusData = {
    sessionId: string;
};

export type BulkImportGetImportStatusResponse = (BulkImportSessionPublic);

export type CustomersGetCustomersData = {
    limit?: number;
    /**
     * Search by name or tel
     */
    search?: (string | null);
    skip?: number;
};

export type CustomersGetCustomersResponse = (CustomersPublic);

export type DebtsReadDebtsData = {
    customerName?: (string | null);
    endDate?: (string | null);
    limit?: number;
    skip?: number;
    startDate?: (string | null);
    status?: (string | null);
};

export type DebtsReadDebtsResponse = (DebtsPublic);

export type DebtsCreateDebtData = {
    requestBody: DebtCreate;
};

export type DebtsCreateDebtResponse = (DebtPublic);

export type DebtsReadDebtData = {
    debtId: string;
};

export type DebtsReadDebtResponse = (DebtPublic);

export type DebtsUpdateDebtData = {
    debtId: string;
    requestBody: DebtUpdate;
};

export type DebtsUpdateDebtResponse = (DebtPublic);

export type DebtsDeleteDebtData = {
    debtId: string;
};

export type DebtsDeleteDebtResponse = (unknown);

export type DebtsCreateDebtPaymentData = {
    debtId: string;
    requestBody: DebtPaymentCreate;
};

export type DebtsCreateDebtPaymentResponse = (DebtPaymentPublic);

export type DebtsReadDebtPaymentsData = {
    debtId: string;
    limit?: number;
    skip?: number;
};

export type DebtsReadDebtPaymentsResponse = (DebtPaymentsPublic);

export type DebtsGetCustomerBalanceData = {
    customerName: string;
};

export type DebtsGetCustomerBalanceResponse = (unknown);

export type ExpensesReadExpenseCategoriesData = {
    limit?: number;
    skip?: number;
};

export type ExpensesReadExpenseCategoriesResponse = (ExpenseCategoriesPublic);

export type ExpensesCreateExpenseCategoryData = {
    requestBody: ExpenseCategoryCreate;
};

export type ExpensesCreateExpenseCategoryResponse = (ExpenseCategoryPublic);

export type ExpensesReadExpenseCategoryData = {
    categoryId: string;
};

export type ExpensesReadExpenseCategoryResponse = (ExpenseCategoryPublic);

export type ExpensesUpdateExpenseCategoryData = {
    categoryId: string;
    requestBody: ExpenseCategoryUpdate;
};

export type ExpensesUpdateExpenseCategoryResponse = (ExpenseCategoryPublic);

export type ExpensesDeleteExpenseCategoryData = {
    categoryId: string;
};

export type ExpensesDeleteExpenseCategoryResponse = (unknown);

export type ExpensesReadExpensesData = {
    categoryId?: (string | null);
    endDate?: (string | null);
    limit?: number;
    search?: (string | null);
    skip?: number;
    startDate?: (string | null);
};

export type ExpensesReadExpensesResponse = (ExpensesPublic);

export type ExpensesCreateExpenseData = {
    requestBody: ExpenseCreate;
};

export type ExpensesCreateExpenseResponse = (ExpensePublic);

export type ExpensesReadExpenseData = {
    expenseId: string;
};

export type ExpensesReadExpenseResponse = (ExpensePublic);

export type ExpensesUpdateExpenseData = {
    expenseId: string;
    requestBody: ExpenseUpdate;
};

export type ExpensesUpdateExpenseResponse = (ExpensePublic);

export type ExpensesDeleteExpenseData = {
    expenseId: string;
};

export type ExpensesDeleteExpenseResponse = (unknown);

export type ExpensesGetExpenseSummaryData = {
    categoryId?: (string | null);
    endDate?: (string | null);
    startDate?: (string | null);
};

export type ExpensesGetExpenseSummaryResponse = (unknown);

export type LoginLoginAccessTokenData = {
    formData: Body_login_login_access_token;
};

export type LoginLoginAccessTokenResponse = (Token);

export type LoginTestTokenResponse = (UserPublic);

export type LoginRecoverPasswordData = {
    email: string;
};

export type LoginRecoverPasswordResponse = (Message);

export type LoginResetPasswordData = {
    requestBody: NewPassword;
};

export type LoginResetPasswordResponse = (Message);

export type LoginRecoverPasswordHtmlContentData = {
    email: string;
};

export type LoginRecoverPasswordHtmlContentResponse = (string);

export type MediaUploadImageData = {
    formData: Body_media_upload_image;
};

export type MediaUploadImageResponse = (MediaPublic);

export type MediaServeImageData = {
    mediaId: string;
};

export type MediaServeImageResponse = (unknown);

export type MediaDeleteMediaData = {
    mediaId: string;
};

export type MediaDeleteMediaResponse = ({
    [key: string]: (string);
});

export type MediaListMediaData = {
    limit?: number;
    skip?: number;
};

export type MediaListMediaResponse = (Array<MediaPublic>);

export type PrivateCreateUserData = {
    requestBody: PrivateUserCreate;
};

export type PrivateCreateUserResponse = (UserPublic);

export type ProductsReadCategoriesResponse = (ProductCategoriesPublic);

export type ProductsReadStatusesResponse = (Array<ProductStatusPublic>);

export type ProductsReadProductsData = {
    categoryId?: (string | null);
    limit?: number;
    name?: (string | null);
    skip?: number;
    statusId?: (string | null);
};

export type ProductsReadProductsResponse = (ProductsPublic);

export type ProductsCreateProductData = {
    requestBody: ProductCreate;
};

export type ProductsCreateProductResponse = (ProductPublic);

export type ProductsReadProductData = {
    id: string;
};

export type ProductsReadProductResponse = (ProductPublic);

export type ProductsUpdateProductData = {
    id: string;
    requestBody: ProductUpdate;
};

export type ProductsUpdateProductResponse = (ProductPublic);

export type ProductsDeleteProductData = {
    id: string;
};

export type ProductsDeleteProductResponse = ({
    [key: string]: (string);
});

export type SalesReadPaymentMethodsData = {
    limit?: number;
    skip?: number;
};

export type SalesReadPaymentMethodsResponse = (PaymentMethodsPublic);

export type SalesCreatePaymentMethodData = {
    requestBody: PaymentMethodCreate;
};

export type SalesCreatePaymentMethodResponse = (PaymentMethodPublic);

export type SalesUpdatePaymentMethodData = {
    paymentMethodId: string;
    requestBody: PaymentMethodUpdate;
};

export type SalesUpdatePaymentMethodResponse = (PaymentMethodPublic);

export type SalesSearchProductsForSaleData = {
    /**
     * Filter by category ID
     */
    categoryId?: (string | null);
    /**
     * Maximum results to return
     */
    limit?: number;
    /**
     * Search query
     */
    q: string;
};

export type SalesSearchProductsForSaleResponse = (Array<ProductPublic>);

export type SalesCreateSaleData = {
    requestBody: SaleCreate;
};

export type SalesCreateSaleResponse = (SalePublic);

export type SalesReadSalesData = {
    /**
     * Filter by product category
     */
    categoryId?: (string | null);
    /**
     * Filter sales until this date
     */
    endDate?: (string | null);
    limit?: number;
    /**
     * Filter by payment method
     */
    paymentMethodId?: (string | null);
    /**
     * Filter by product ID
     */
    productId?: (string | null);
    skip?: number;
    /**
     * Filter sales from this date
     */
    startDate?: (string | null);
};

export type SalesReadSalesResponse = (SalesPublic);

export type SalesCreateSaleWithMultiplePaymentsData = {
    requestBody: MultiPaymentSaleCreate;
};

export type SalesCreateSaleWithMultiplePaymentsResponse = (SalePublic);

export type SalesReadSalePaymentsData = {
    saleId: string;
};

export type SalesReadSalePaymentsResponse = (Array<SalePaymentPublic>);

export type SalesGetTodaySalesSummaryResponse = ({
    [key: string]: unknown;
});

export type SalesReadSaleData = {
    saleId: string;
};

export type SalesReadSaleResponse = (SalePublic);

export type SalesDeleteSaleData = {
    saleId: string;
};

export type SalesDeleteSaleResponse = (unknown);

export type ShiftReconciliationCreateShiftReconciliationData = {
    requestBody: ShiftReconciliationCreate;
};

export type ShiftReconciliationCreateShiftReconciliationResponse = (ShiftReconciliationPublic);

export type ShiftReconciliationReadShiftReconciliationsData = {
    /**
     * Filter until this date
     */
    endDate?: (string | null);
    limit?: number;
    skip?: number;
    /**
     * Filter from this date
     */
    startDate?: (string | null);
};

export type ShiftReconciliationReadShiftReconciliationsResponse = (ShiftReconciliationsPublic);

export type ShiftReconciliationReadShiftReconciliationData = {
    shiftId: string;
};

export type ShiftReconciliationReadShiftReconciliationResponse = (ShiftReconciliationPublic);

export type ShiftReconciliationUpdateShiftReconciliationData = {
    requestBody: ShiftReconciliationUpdate;
    shiftId: string;
};

export type ShiftReconciliationUpdateShiftReconciliationResponse = (ShiftReconciliationPublic);

export type ShiftReconciliationGetCurrentCashSummaryData = {
    /**
     * End date (defaults to today)
     */
    endDate?: (string | null);
    /**
     * Start date (defaults to today)
     */
    startDate?: (string | null);
};

export type ShiftReconciliationGetCurrentCashSummaryResponse = ({
    [key: string]: unknown;
});

export type StockEntriesSearchProductsForStockEntryData = {
    /**
     * Maximum results to return
     */
    limit?: number;
    /**
     * Search query
     */
    q: string;
};

export type StockEntriesSearchProductsForStockEntryResponse = (Array<ProductPublic>);

export type StockEntriesReadStockEntriesData = {
    limit?: number;
    productId?: (string | null);
    skip?: number;
};

export type StockEntriesReadStockEntriesResponse = (StockEntriesPublic);

export type StockEntriesCreateStockEntryData = {
    requestBody: StockEntryCreate;
};

export type StockEntriesCreateStockEntryResponse = (StockEntryPublic);

export type StockEntriesReadStockEntryData = {
    id: string;
};

export type StockEntriesReadStockEntryResponse = (StockEntryPublic);

export type StockEntriesUpdateStockEntryData = {
    id: string;
    requestBody: StockEntryUpdate;
};

export type StockEntriesUpdateStockEntryResponse = (StockEntryPublic);

export type StockEntriesDeleteStockEntryData = {
    id: string;
};

export type StockEntriesDeleteStockEntryResponse = ({
    [key: string]: (string);
});

export type UsersReadUsersData = {
    limit?: number;
    skip?: number;
};

export type UsersReadUsersResponse = (UsersPublic);

export type UsersCreateUserData = {
    requestBody: UserCreate;
};

export type UsersCreateUserResponse = (UserPublic);

export type UsersReadUserMeResponse = (UserPublic);

export type UsersDeleteUserMeResponse = (Message);

export type UsersUpdateUserMeData = {
    requestBody: UserUpdateMe;
};

export type UsersUpdateUserMeResponse = (UserPublic);

export type UsersUpdatePasswordMeData = {
    requestBody: UpdatePassword;
};

export type UsersUpdatePasswordMeResponse = (Message);

export type UsersRegisterUserData = {
    requestBody: UserRegister;
};

export type UsersRegisterUserResponse = (UserPublic);

export type UsersReadUserByIdData = {
    userId: string;
};

export type UsersReadUserByIdResponse = (UserPublic);

export type UsersUpdateUserData = {
    requestBody: UserUpdate;
    userId: string;
};

export type UsersUpdateUserResponse = (UserPublic);

export type UsersDeleteUserData = {
    userId: string;
};

export type UsersDeleteUserResponse = (Message);

export type UtilsTestEmailData = {
    emailTo: string;
};

export type UtilsTestEmailResponse = (Message);

export type UtilsHealthCheckResponse = (boolean);