name: General Issue
description: Report a bug, suggest a feature, or ask a question about the project.
body:
  - type: markdown
    attributes:
      value: |
        Thanks for your interest in this project!

        Before creating an issue, please check if a similar issue already exists. When reporting bugs or suggesting features, please provide as much detail as possible to help us understand and address your concern.
  - type: textarea
    id: content
    attributes:
      label: Issue Content
      description: Please describe your issue, feature request, or question in detail. Include steps to reproduce for bugs, or explain what you'd like to achieve for feature requests.
      placeholder: |
        For bug reports:
        - What happened?
        - What did you expect to happen?
        - Steps to reproduce
        - Environment details (OS, browser, etc.)
        
        For feature requests:
        - What would you like to achieve?
        - Why is this feature useful?
        - Any alternative solutions you've considered?

name: General Issue
description: Report a bug, suggest a feature, or ask a question about the project.
body:
  - type: markdown
    attributes:
      value: |
        Thanks for your interest in this project! 🚀

        Before creating an issue, please check if a similar issue already exists. When reporting bugs or suggesting features, please provide as much detail as possible to help us understand and address your concern.
  - type: textarea
    id: content
    attributes:
      label: Issue Content
      description: Please describe your issue, feature request, or question in detail. Include steps to reproduce for bugs, or explain what you'd like to achieve for feature requests.
      placeholder: |
        For bug reports:
        - What happened?
        - What did you expect to happen?
        - Steps to reproduce
        - Environment details (OS, browser, etc.)
        
        For feature requests:
        - What would you like to achieve?
        - Why is this feature useful?
        - Any alternative solutions you've considered?
