"""empty message

Revision ID: 39649eee44f0
Revises: 125c8b1e479f
Create Date: 2025-11-23 11:27:44.282471

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '39649eee44f0'
down_revision = '125c8b1e479f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('till_shift',
    sa.Column('shift_type', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('opening_cash_float', sa.Numeric(scale=2), nullable=False),
    sa.Column('opening_balance', sa.Numeric(scale=2), nullable=True),
    sa.Column('opening_time', sa.DateTime(), nullable=False),
    sa.Column('closing_time', sa.DateTime(), nullable=True),
    sa.Column('closing_cash_float', sa.Numeric(scale=2), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(length=2000), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('opened_by_id', sa.Uuid(), nullable=False),
    sa.Column('closed_by_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['closed_by_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['opened_by_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cashier_variance',
    sa.Column('till_shift_id', sa.Uuid(), nullable=False),
    sa.Column('cashier_id', sa.Uuid(), nullable=False),
    sa.Column('total_variance', sa.Numeric(scale=2), nullable=False),
    sa.Column('variance_type', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(length=2000), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['cashier_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['till_shift_id'], ['till_shift.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('payment_method_reconciliation',
    sa.Column('payment_method_id', sa.Uuid(), nullable=False),
    sa.Column('system_count', sa.Numeric(scale=2), nullable=False),
    sa.Column('physical_count', sa.Numeric(scale=2), nullable=False),
    sa.Column('variance', sa.Numeric(scale=2), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('shift_reconciliation_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['payment_method_id'], ['payment_method.id'], ),
    sa.ForeignKeyConstraint(['shift_reconciliation_id'], ['shift_reconciliation.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # Drop dependent tables first (in correct order - drop children before parents)
    # Use IF EXISTS to avoid errors if tables/indexes don't exist
    op.execute("DROP INDEX IF EXISTS ix_credit_note_credit_note_number")
    op.execute("DROP TABLE IF EXISTS credit_note CASCADE")  # Drop credit_note first (depends on sale_transaction)
    op.execute("DROP TABLE IF EXISTS sale_item CASCADE")  # Drop sale_item (depends on sale_transaction)
    op.execute("DROP INDEX IF EXISTS ix_sale_transaction_receipt_number")
    op.execute("DROP INDEX IF EXISTS ix_sale_transaction_transaction_date")
    op.execute("DROP TABLE IF EXISTS sale_transaction CASCADE")  # Now safe to drop sale_transaction
    op.execute("DROP INDEX IF EXISTS ix_suspended_sale_suspended_at")
    op.execute("DROP TABLE IF EXISTS suspended_sale CASCADE")  # Drop suspended_sale (depends on customer)
    op.execute("DROP INDEX IF EXISTS ix_customer_name")
    op.execute("DROP TABLE IF EXISTS customer CASCADE")  # Drop customer last
    op.execute("DROP INDEX IF EXISTS ix_cash_movement_movement_date")
    op.execute("DROP TABLE IF EXISTS cash_movement CASCADE")
    # Drop indexes conditionally (using IF EXISTS to avoid errors)
    op.execute("DROP INDEX IF EXISTS idx_grn_creates_debt")
    op.execute("DROP INDEX IF EXISTS idx_grn_payment_type")
    op.execute("DROP INDEX IF EXISTS idx_grn_requires_approval")
    op.execute("DROP INDEX IF EXISTS idx_notification_created_at")
    op.execute("DROP INDEX IF EXISTS idx_notification_is_read")
    op.execute("DROP INDEX IF EXISTS idx_notification_priority")
    op.execute("DROP INDEX IF EXISTS idx_notification_type")
    op.execute("DROP INDEX IF EXISTS idx_notification_user_id")
    op.execute("DROP INDEX IF EXISTS idx_product_enable_reorder_alerts")
    op.execute("DROP INDEX IF EXISTS idx_product_last_reorder_alert_sent")
    op.execute("DROP INDEX IF EXISTS idx_reminder_log_sent_at")
    op.execute("DROP INDEX IF EXISTS idx_reminder_log_setting_id")
    op.execute("DROP INDEX IF EXISTS idx_reminder_log_status")
    op.execute("DROP INDEX IF EXISTS idx_reminder_log_user_id")
    op.execute("DROP INDEX IF EXISTS idx_reminder_setting_enabled")
    op.execute("DROP INDEX IF EXISTS idx_reminder_setting_next_send")
    op.execute("DROP INDEX IF EXISTS idx_reminder_setting_type")
    op.execute("DROP INDEX IF EXISTS idx_reminder_setting_user_id")
    op.add_column('shift_reconciliation', sa.Column('till_shift_id', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'shift_reconciliation', 'till_shift', ['till_shift_id'], ['id'])
    op.execute("DROP INDEX IF EXISTS idx_supplier_debt_due_date")
    op.execute("DROP INDEX IF EXISTS idx_supplier_debt_grn_id")
    op.execute("DROP INDEX IF EXISTS idx_supplier_debt_is_overdue")
    op.execute("DROP INDEX IF EXISTS idx_supplier_debt_status")
    op.execute("DROP INDEX IF EXISTS idx_supplier_debt_supplier_id")
    op.execute("DROP INDEX IF EXISTS idx_supplier_debt_installment_debt_id")
    op.execute("DROP INDEX IF EXISTS idx_supplier_debt_installment_due_date")
    op.execute("DROP INDEX IF EXISTS idx_supplier_debt_installment_status")
    op.execute("DROP INDEX IF EXISTS idx_supplier_debt_payment_date")
    op.execute("DROP INDEX IF EXISTS idx_supplier_debt_payment_debt_id")
    op.execute("DROP INDEX IF EXISTS idx_supplier_debt_payment_installment_id")
    op.execute("DROP INDEX IF EXISTS idx_supplier_product_reorder_active")
    op.execute("DROP INDEX IF EXISTS idx_supplier_product_reorder_product_id")
    op.execute("DROP INDEX IF EXISTS idx_supplier_product_reorder_supplier_id")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('idx_supplier_product_reorder_supplier_id'), 'supplier_product_reorder', ['supplier_id'], unique=False)
    op.create_index(op.f('idx_supplier_product_reorder_product_id'), 'supplier_product_reorder', ['product_id'], unique=False)
    op.create_index(op.f('idx_supplier_product_reorder_active'), 'supplier_product_reorder', ['is_active'], unique=False)
    op.create_index(op.f('idx_supplier_debt_payment_installment_id'), 'supplier_debt_payment', ['installment_id'], unique=False)
    op.create_index(op.f('idx_supplier_debt_payment_debt_id'), 'supplier_debt_payment', ['supplier_debt_id'], unique=False)
    op.create_index(op.f('idx_supplier_debt_payment_date'), 'supplier_debt_payment', ['payment_date'], unique=False)
    op.create_index(op.f('idx_supplier_debt_installment_status'), 'supplier_debt_installment', ['status'], unique=False)
    op.create_index(op.f('idx_supplier_debt_installment_due_date'), 'supplier_debt_installment', ['due_date'], unique=False)
    op.create_index(op.f('idx_supplier_debt_installment_debt_id'), 'supplier_debt_installment', ['supplier_debt_id'], unique=False)
    op.create_index(op.f('idx_supplier_debt_supplier_id'), 'supplier_debt', ['supplier_id'], unique=False)
    op.create_index(op.f('idx_supplier_debt_status'), 'supplier_debt', ['status'], unique=False)
    op.create_index(op.f('idx_supplier_debt_is_overdue'), 'supplier_debt', ['is_overdue'], unique=False)
    op.create_index(op.f('idx_supplier_debt_grn_id'), 'supplier_debt', ['grn_id'], unique=False)
    op.create_index(op.f('idx_supplier_debt_due_date'), 'supplier_debt', ['due_date'], unique=False)
    op.drop_constraint(None, 'shift_reconciliation', type_='foreignkey')
    op.drop_column('shift_reconciliation', 'till_shift_id')
    op.create_index(op.f('idx_reminder_setting_user_id'), 'reminder_setting', ['user_id'], unique=False)
    op.create_index(op.f('idx_reminder_setting_type'), 'reminder_setting', ['reminder_type'], unique=False)
    op.create_index(op.f('idx_reminder_setting_next_send'), 'reminder_setting', ['next_send_at'], unique=False)
    op.create_index(op.f('idx_reminder_setting_enabled'), 'reminder_setting', ['is_enabled'], unique=False)
    op.create_index(op.f('idx_reminder_log_user_id'), 'reminder_log', ['user_id'], unique=False)
    op.create_index(op.f('idx_reminder_log_status'), 'reminder_log', ['status'], unique=False)
    op.create_index(op.f('idx_reminder_log_setting_id'), 'reminder_log', ['reminder_setting_id'], unique=False)
    op.create_index(op.f('idx_reminder_log_sent_at'), 'reminder_log', ['sent_at'], unique=False)
    op.create_index(op.f('idx_product_last_reorder_alert_sent'), 'product', ['last_reorder_alert_sent'], unique=False)
    op.create_index(op.f('idx_product_enable_reorder_alerts'), 'product', ['enable_reorder_alerts'], unique=False)
    op.create_index(op.f('idx_notification_user_id'), 'notification', ['user_id'], unique=False)
    op.create_index(op.f('idx_notification_type'), 'notification', ['notification_type'], unique=False)
    op.create_index(op.f('idx_notification_priority'), 'notification', ['priority'], unique=False)
    op.create_index(op.f('idx_notification_is_read'), 'notification', ['is_read'], unique=False)
    op.create_index(op.f('idx_notification_created_at'), 'notification', ['created_at'], unique=False)
    op.create_index(op.f('idx_grn_requires_approval'), 'grn', ['requires_approval'], unique=False)
    op.create_index(op.f('idx_grn_payment_type'), 'grn', ['payment_type'], unique=False)
    op.create_index(op.f('idx_grn_creates_debt'), 'grn', ['creates_debt'], unique=False)
    op.create_table('cash_movement',
    sa.Column('movement_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('amount', sa.NUMERIC(), autoincrement=False, nullable=False),
    sa.Column('reason', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('notes', sa.VARCHAR(length=1000), autoincrement=False, nullable=True),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('movement_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('created_by_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['user.id'], name=op.f('cash_movement_created_by_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('cash_movement_pkey'))
    )
    op.create_index(op.f('ix_cash_movement_movement_date'), 'cash_movement', ['movement_date'], unique=False)
    op.create_table('sale_item',
    sa.Column('product_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('quantity', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('unit_price', sa.NUMERIC(), autoincrement=False, nullable=False),
    sa.Column('discount_amount', sa.NUMERIC(), autoincrement=False, nullable=False),
    sa.Column('discount_percent', sa.NUMERIC(), autoincrement=False, nullable=False),
    sa.Column('total_amount', sa.NUMERIC(), autoincrement=False, nullable=False),
    sa.Column('transaction_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], name=op.f('sale_item_product_id_fkey')),
    sa.ForeignKeyConstraint(['transaction_id'], ['sale_transaction.id'], name=op.f('sale_item_transaction_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('sale_item_pkey'))
    )
    op.create_table('sale_transaction',
    sa.Column('customer_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('subtotal', sa.NUMERIC(), autoincrement=False, nullable=False),
    sa.Column('discount_amount', sa.NUMERIC(), autoincrement=False, nullable=False),
    sa.Column('discount_percent', sa.NUMERIC(), autoincrement=False, nullable=False),
    sa.Column('tax_amount', sa.NUMERIC(), autoincrement=False, nullable=False),
    sa.Column('tax_percent', sa.NUMERIC(), autoincrement=False, nullable=False),
    sa.Column('total_amount', sa.NUMERIC(), autoincrement=False, nullable=False),
    sa.Column('payment_method_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('amount_received', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('change_amount', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('receipt_number', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('notes', sa.VARCHAR(length=1000), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('transaction_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('created_by_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('voided', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('void_reason', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['user.id'], name='sale_transaction_created_by_id_fkey'),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], name='sale_transaction_customer_id_fkey'),
    sa.ForeignKeyConstraint(['payment_method_id'], ['payment_method.id'], name='sale_transaction_payment_method_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='sale_transaction_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index(op.f('ix_sale_transaction_transaction_date'), 'sale_transaction', ['transaction_date'], unique=False)
    op.create_index(op.f('ix_sale_transaction_receipt_number'), 'sale_transaction', ['receipt_number'], unique=False)
    op.create_table('credit_note',
    sa.Column('original_sale_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('customer_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('reason', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.Column('total_amount', sa.NUMERIC(), autoincrement=False, nullable=False),
    sa.Column('items_data', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('notes', sa.VARCHAR(length=1000), autoincrement=False, nullable=True),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('credit_note_number', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('created_by_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['user.id'], name=op.f('credit_note_created_by_id_fkey')),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], name=op.f('credit_note_customer_id_fkey')),
    sa.ForeignKeyConstraint(['original_sale_id'], ['sale_transaction.id'], name=op.f('credit_note_original_sale_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('credit_note_pkey')),
    sa.UniqueConstraint('credit_note_number', name=op.f('credit_note_credit_note_number_key'))
    )
    op.create_index(op.f('ix_credit_note_credit_note_number'), 'credit_note', ['credit_note_number'], unique=True)
    op.create_table('suspended_sale',
    sa.Column('customer_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('subtotal', sa.NUMERIC(), autoincrement=False, nullable=False),
    sa.Column('discount_amount', sa.NUMERIC(), autoincrement=False, nullable=False),
    sa.Column('discount_percent', sa.NUMERIC(), autoincrement=False, nullable=False),
    sa.Column('tax_amount', sa.NUMERIC(), autoincrement=False, nullable=False),
    sa.Column('tax_percent', sa.NUMERIC(), autoincrement=False, nullable=False),
    sa.Column('total_amount', sa.NUMERIC(), autoincrement=False, nullable=False),
    sa.Column('items_data', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('notes', sa.VARCHAR(length=1000), autoincrement=False, nullable=True),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('suspended_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('created_by_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('resumed_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('is_resumed', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['user.id'], name=op.f('suspended_sale_created_by_id_fkey')),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], name=op.f('suspended_sale_customer_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('suspended_sale_pkey'))
    )
    op.create_index(op.f('ix_suspended_sale_suspended_at'), 'suspended_sale', ['suspended_at'], unique=False)
    op.create_table('customer',
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('contact', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('email', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('address', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('customer_pin', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('balance', sa.NUMERIC(), autoincrement=False, nullable=False),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('customer_pkey'))
    )
    op.create_index(op.f('ix_customer_name'), 'customer', ['name'], unique=False)
    op.drop_table('payment_method_reconciliation')
    op.drop_table('cashier_variance')
    op.drop_table('till_shift')
    # ### end Alembic commands ###
