"""make_product_tag_id_required

Revision ID: 88135429081f
Revises: fd69c021f227
Create Date: 2025-11-12 10:55:22.072119

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "88135429081f"
down_revision = "fd69c021f227"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("product", "tag_id", existing_type=sa.UUID(), nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("product", "tag_id", existing_type=sa.UUID(), nullable=True)
    # ### end Alembic commands ###
