"""update_media_table_for_file_upload

Revision ID: 9fd90704b796
Revises: 88135429081f
Create Date: 2025-11-13 10:55:55.288716

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '9fd90704b796'
down_revision = '88135429081f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('media', sa.Column('file_path', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=False))
    op.drop_constraint(op.f('media_uuid_key'), 'media', type_='unique')
    op.drop_column('media', 'uuid')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('media', sa.Column('uuid', sa.VARCHAR(length=36), autoincrement=False, nullable=False))
    op.create_unique_constraint(op.f('media_uuid_key'), 'media', ['uuid'])
    op.drop_column('media', 'file_path')
    # ### end Alembic commands ###
