"""add_grn_supplier_transporter_tables

Revision ID: dc3fa9d8106e
Revises: add_sale_payment
Create Date: 2025-11-22 20:57:31.417779

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'dc3fa9d8106e'
down_revision = 'add_sale_payment'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('supplier',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('contact_person', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('phone', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('address', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_supplier_name'), 'supplier', ['name'], unique=False)
    op.create_table('transporter',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('contact_person', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('phone', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('vehicle_registration', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transporter_name'), 'transporter', ['name'], unique=False)
    op.create_table('grn',
    sa.Column('supplier_id', sa.Uuid(), nullable=False),
    sa.Column('transporter_id', sa.Uuid(), nullable=True),
    sa.Column('transaction_date', sa.DateTime(), nullable=False),
    sa.Column('goods_receipt_date', sa.DateTime(), nullable=False),
    sa.Column('shipping_address', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('delivery_number', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('delivery_date', sa.DateTime(), nullable=True),
    sa.Column('consignment_number', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('consignment_date', sa.DateTime(), nullable=True),
    sa.Column('batch_number', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('driver_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('vehicle_reg_number', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('department', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('section', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('currency', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=False),
    sa.Column('total_amount', sa.Numeric(scale=2), nullable=False),
    sa.Column('is_approved', sa.Boolean(), nullable=False),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('approved_by_id', sa.Uuid(), nullable=True),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(length=2000), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('grn_number', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('created_by_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['approved_by_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['created_by_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['supplier_id'], ['supplier.id'], ),
    sa.ForeignKeyConstraint(['transporter_id'], ['transporter.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_grn_grn_number'), 'grn', ['grn_number'], unique=False)
    op.create_table('grn_item',
    sa.Column('grn_id', sa.Uuid(), nullable=False),
    sa.Column('product_id', sa.Uuid(), nullable=False),
    sa.Column('order_quantity', sa.Numeric(scale=2), nullable=False),
    sa.Column('pending_quantity', sa.Numeric(scale=2), nullable=False),
    sa.Column('received_quantity', sa.Numeric(scale=2), nullable=False),
    sa.Column('lpo_number', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('ledger_account', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('is_promo', sa.Boolean(), nullable=False),
    sa.Column('unit_price', sa.Numeric(scale=2), nullable=True),
    sa.Column('total_price', sa.Numeric(scale=2), nullable=True),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['grn_id'], ['grn.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_index(op.f('ix_sale_product_date'), table_name='sale')
    op.drop_index(op.f('ix_sale_user_date'), table_name='sale')
    op.alter_column('sale_payment', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False)
    op.alter_column('sale_payment', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False)
    op.drop_index(op.f('ix_sale_payment_sale_id'), table_name='sale_payment')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_sale_payment_sale_id'), 'sale_payment', ['sale_id'], unique=False)
    op.alter_column('sale_payment', 'updated_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False)
    op.alter_column('sale_payment', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False)
    op.create_index(op.f('ix_sale_user_date'), 'sale', ['created_by_id', 'sale_date'], unique=False)
    op.create_index(op.f('ix_sale_product_date'), 'sale', ['product_id', 'sale_date'], unique=False)
    op.drop_table('grn_item')
    op.drop_index(op.f('ix_grn_grn_number'), table_name='grn')
    op.drop_table('grn')
    op.drop_index(op.f('ix_transporter_name'), table_name='transporter')
    op.drop_table('transporter')
    op.drop_index(op.f('ix_supplier_name'), table_name='supplier')
    op.drop_table('supplier')
    # ### end Alembic commands ###
