/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RecoverPasswordRouteImport } from './routes/recover-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as LayoutIndexRouteImport } from './routes/_layout/index'
import { Route as LayoutStockEntyRouteImport } from './routes/_layout/stock-enty'
import { Route as LayoutShiftReconciliationRouteImport } from './routes/_layout/shift-reconciliation'
import { Route as LayoutSettingsRouteImport } from './routes/_layout/settings'
import { Route as LayoutSalesRouteImport } from './routes/_layout/sales'
import { Route as LayoutReportsRouteImport } from './routes/_layout/reports'
import { Route as LayoutProductsRouteImport } from './routes/_layout/products'
import { Route as LayoutItemsRouteImport } from './routes/_layout/items'
import { Route as LayoutExpensesRouteImport } from './routes/_layout/expenses'
import { Route as LayoutDebtsRouteImport } from './routes/_layout/debts'
import { Route as LayoutAdminRouteImport } from './routes/_layout/admin'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RecoverPasswordRoute = RecoverPasswordRouteImport.update({
  id: '/recover-password',
  path: '/recover-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutIndexRoute = LayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutStockEntyRoute = LayoutStockEntyRouteImport.update({
  id: '/stock-enty',
  path: '/stock-enty',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutShiftReconciliationRoute =
  LayoutShiftReconciliationRouteImport.update({
    id: '/shift-reconciliation',
    path: '/shift-reconciliation',
    getParentRoute: () => LayoutRoute,
  } as any)
const LayoutSettingsRoute = LayoutSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutSalesRoute = LayoutSalesRouteImport.update({
  id: '/sales',
  path: '/sales',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutReportsRoute = LayoutReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutProductsRoute = LayoutProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutItemsRoute = LayoutItemsRouteImport.update({
  id: '/items',
  path: '/items',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutExpensesRoute = LayoutExpensesRouteImport.update({
  id: '/expenses',
  path: '/expenses',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutDebtsRoute = LayoutDebtsRouteImport.update({
  id: '/debts',
  path: '/debts',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAdminRoute = LayoutAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => LayoutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/admin': typeof LayoutAdminRoute
  '/debts': typeof LayoutDebtsRoute
  '/expenses': typeof LayoutExpensesRoute
  '/items': typeof LayoutItemsRoute
  '/products': typeof LayoutProductsRoute
  '/reports': typeof LayoutReportsRoute
  '/sales': typeof LayoutSalesRoute
  '/settings': typeof LayoutSettingsRoute
  '/shift-reconciliation': typeof LayoutShiftReconciliationRoute
  '/stock-enty': typeof LayoutStockEntyRoute
  '/': typeof LayoutIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/admin': typeof LayoutAdminRoute
  '/debts': typeof LayoutDebtsRoute
  '/expenses': typeof LayoutExpensesRoute
  '/items': typeof LayoutItemsRoute
  '/products': typeof LayoutProductsRoute
  '/reports': typeof LayoutReportsRoute
  '/sales': typeof LayoutSalesRoute
  '/settings': typeof LayoutSettingsRoute
  '/shift-reconciliation': typeof LayoutShiftReconciliationRoute
  '/stock-enty': typeof LayoutStockEntyRoute
  '/': typeof LayoutIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_layout': typeof LayoutRouteWithChildren
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/_layout/admin': typeof LayoutAdminRoute
  '/_layout/debts': typeof LayoutDebtsRoute
  '/_layout/expenses': typeof LayoutExpensesRoute
  '/_layout/items': typeof LayoutItemsRoute
  '/_layout/products': typeof LayoutProductsRoute
  '/_layout/reports': typeof LayoutReportsRoute
  '/_layout/sales': typeof LayoutSalesRoute
  '/_layout/settings': typeof LayoutSettingsRoute
  '/_layout/shift-reconciliation': typeof LayoutShiftReconciliationRoute
  '/_layout/stock-enty': typeof LayoutStockEntyRoute
  '/_layout/': typeof LayoutIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/admin'
    | '/debts'
    | '/expenses'
    | '/items'
    | '/products'
    | '/reports'
    | '/sales'
    | '/settings'
    | '/shift-reconciliation'
    | '/stock-enty'
    | '/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/admin'
    | '/debts'
    | '/expenses'
    | '/items'
    | '/products'
    | '/reports'
    | '/sales'
    | '/settings'
    | '/shift-reconciliation'
    | '/stock-enty'
    | '/'
  id:
    | '__root__'
    | '/_layout'
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/_layout/admin'
    | '/_layout/debts'
    | '/_layout/expenses'
    | '/_layout/items'
    | '/_layout/products'
    | '/_layout/reports'
    | '/_layout/sales'
    | '/_layout/settings'
    | '/_layout/shift-reconciliation'
    | '/_layout/stock-enty'
    | '/_layout/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LayoutRoute: typeof LayoutRouteWithChildren
  LoginRoute: typeof LoginRoute
  RecoverPasswordRoute: typeof RecoverPasswordRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recover-password': {
      id: '/recover-password'
      path: '/recover-password'
      fullPath: '/recover-password'
      preLoaderRoute: typeof RecoverPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/stock-enty': {
      id: '/_layout/stock-enty'
      path: '/stock-enty'
      fullPath: '/stock-enty'
      preLoaderRoute: typeof LayoutStockEntyRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/shift-reconciliation': {
      id: '/_layout/shift-reconciliation'
      path: '/shift-reconciliation'
      fullPath: '/shift-reconciliation'
      preLoaderRoute: typeof LayoutShiftReconciliationRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/settings': {
      id: '/_layout/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof LayoutSettingsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/sales': {
      id: '/_layout/sales'
      path: '/sales'
      fullPath: '/sales'
      preLoaderRoute: typeof LayoutSalesRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/reports': {
      id: '/_layout/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof LayoutReportsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/products': {
      id: '/_layout/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof LayoutProductsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/items': {
      id: '/_layout/items'
      path: '/items'
      fullPath: '/items'
      preLoaderRoute: typeof LayoutItemsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/expenses': {
      id: '/_layout/expenses'
      path: '/expenses'
      fullPath: '/expenses'
      preLoaderRoute: typeof LayoutExpensesRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/debts': {
      id: '/_layout/debts'
      path: '/debts'
      fullPath: '/debts'
      preLoaderRoute: typeof LayoutDebtsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/admin': {
      id: '/_layout/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof LayoutAdminRouteImport
      parentRoute: typeof LayoutRoute
    }
  }
}

interface LayoutRouteChildren {
  LayoutAdminRoute: typeof LayoutAdminRoute
  LayoutDebtsRoute: typeof LayoutDebtsRoute
  LayoutExpensesRoute: typeof LayoutExpensesRoute
  LayoutItemsRoute: typeof LayoutItemsRoute
  LayoutProductsRoute: typeof LayoutProductsRoute
  LayoutReportsRoute: typeof LayoutReportsRoute
  LayoutSalesRoute: typeof LayoutSalesRoute
  LayoutSettingsRoute: typeof LayoutSettingsRoute
  LayoutShiftReconciliationRoute: typeof LayoutShiftReconciliationRoute
  LayoutStockEntyRoute: typeof LayoutStockEntyRoute
  LayoutIndexRoute: typeof LayoutIndexRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutAdminRoute: LayoutAdminRoute,
  LayoutDebtsRoute: LayoutDebtsRoute,
  LayoutExpensesRoute: LayoutExpensesRoute,
  LayoutItemsRoute: LayoutItemsRoute,
  LayoutProductsRoute: LayoutProductsRoute,
  LayoutReportsRoute: LayoutReportsRoute,
  LayoutSalesRoute: LayoutSalesRoute,
  LayoutSettingsRoute: LayoutSettingsRoute,
  LayoutShiftReconciliationRoute: LayoutShiftReconciliationRoute,
  LayoutStockEntyRoute: LayoutStockEntyRoute,
  LayoutIndexRoute: LayoutIndexRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  LayoutRoute: LayoutRouteWithChildren,
  LoginRoute: LoginRoute,
  RecoverPasswordRoute: RecoverPasswordRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
